import type { Intensity } from "../../types";

/** Insider tropes — rotate across prompts and offline pools. */
export const ARCHITECT_GRILL_ON = [
  "render vs built / golden hour vs field mud",
  "section headroom vs render people on the roof",
  "revision clouds vs minimalism branding",
  "site visit cosplay vs inbox RFI avalanche",
  "ceiling height lie on drawing vs MEP field measure",
  "floating / sculptural stair vs OSHA and handrail reality",
  "curtain wall detail as jewelry — waterproofing as rumor",
  "design intent slide deck vs dimension string 'see model'",
  "MEP hidden in reflected ceiling plan",
  "door hardware schedule as unfinished novel",
  "door swing treated as philosophy not geometry",
  "parti diagram simplicity vs construction admin chaos",
  "Horizon / Nexus / Latin project naming vs strip-mall budget",
  "facade museum quality vs back-of-house soul missing",
  "value engineering the part that kept water out",
  "constructibility review on calendar — not in attendance",
  "charrette as spa day for egos",
  "submittal review speed vs submittal quality",
  "life safety plan vs render lifestyle on roof",
  "cantilever because gravity is someone else's contract",
  "flashing detail energy missing behind black turtleneck",
  "sheet index War and Peace — building is footnote",
  "coordination meeting invite — architect on site photo shoot",
  "punch list 'accept as design intent'",
  "SD/DD/CD phase promises vs IFC reality",
  "material board chef's kiss — detail section shrug",
  "wall section two lines and a prayer",
  "stair moved fourteen times — still called minimal",
  "design narrative poetry — dimension strings vandalism",
  "VE deleted facade — kept render for marketing",
];

export const ARCHITECT_AVOID = [
  "clash matrices and federated model divorce (BIM/VDC)",
  "buyout spreadsheets and GMP fiction (precon/GC)",
  "stamping structural calcs (structural engineer)",
  "superintendent daily reports and hammer jokes",
  "running Navisworks as primary job",
  "duct rough-in in plenum (MEP contractor)",
  "sprinkler head hanger fights (fire protection trade)",
  "takeoff quantities and bid spread (estimator)",
];

/** API variation hints — large pool for live roasts. */
export const ARCHITECT_ANGLES = [
  "Render laughing people — section has no headroom.",
  "Horizon/Nexus project name — black turtleneck energy.",
  "Revision clouds maximalist — minimalism is marketing.",
  "Floating stair — physics wants a meeting you skip.",
  "Ceiling plan where MEP goes to fight for air.",
  "Curtain wall meeting: glass, hope, and leakage.",
  "Design intent 40 slides — one dimension says see model.",
  "Site visit once for content — inbox daily for blood.",
  "Waterproofing detail is a ghost — facade is jewelry.",
  "Door swing conflict with reality and with itself.",
  "Parti diagram rectangle — CA is non-Euclidean.",
  "Reflected ceiling plan — structure vanished, magic trick.",
  "Handrail theoretical on sculptural stair.",
  "Cantilever — gravity is someone else's contract.",
  "VE killed the part that kept water out.",
  "Constructibility review scheduled — attendance optional.",
  "Material board stunning — flashing detail missing.",
  "Sheet index novel — building is footnote.",
  "RFI answer haiku — hurts to read.",
  "Punch list note: accept as design intent.",
  "Back-of-house where souls go missing — facade is museum.",
  "Stair Bauhaus on paper — OSHA fan fiction built.",
  "Charrette: spa day for egos, hell for trades.",
  "Render golden hour — field photo overcast forever.",
  "Life safety plan vs render rooftop party.",
  "Wall section two lines — prayer included.",
  "Door hardware schedule — rumor with aspirations.",
  "You hide MEP like a smuggler in the ceiling.",
  "Fourteen stair revisions — still minimal, somehow.",
  "Black turtleneck strong — flashing detail weak.",
  "Design vision clear — constructibility negotiable.",
  "You visit site for photos — super visits your RFIs.",
  "Schematic is vibe — construction set is war.",
  "You love a reveal — framer loves a wall that exists.",
  "Value engineering your own waterproofing — bold.",
  "Coordination call — you sent a delegate and a mood board.",
  "Elevation sketch sculptural — section headroom fictional.",
  "You named it Latin — budget named it value engineering.",
  "Your redlines polite — superintendent side-eye not.",
  "IFC drop Friday — field Monday trust issues.",
  "You don't detail — you imply and transmittal.",
  "Render has trees — landscape contractor has questions.",
  "Ceiling height 14 feet on paper — 9'-2\" in the plenum.",
  "You moved the stair — the field felt it spiritually.",
  "Design intent slide — trades want a dimension string.",
  "You're why spec says architect shall review submittals.",
  "Facade detail jewelry — WRB continuity rumor.",
  "Your inbox is RFIs — your calendar is charrettes.",
  "Minimalism aesthetic — maximalist revision clouds.",
  "You sell clarity of vision — deliver scavenger hunt PDF.",
  "AI replaces you — they call it #AI'sB#@$H, lovingly.",
];

export const ARCHITECT_ROAST_LINES: Record<Intensity, string[]> = {
  light: [
    "Hi {name}! Your render has people on the roof — your section forgot headroom.",
    "Hi {name}! You named it Horizon — the budget named it value engineering.",
    "Hi {name}! Minimalism is the brand — revision clouds are the hobby.",
    "Hi {name}! Your material board is chef's kiss — your flashing detail is TBD.",
    "Hi {name}! You love a cantilever — physics sends its regards.",
    "Hi {name}! Site visit once for photos — superintendent lives in your inbox.",
    "Hi {name}! Your parti diagram is a rectangle — your CA set is a thriller.",
    "Hi {name}! 'Final' is your favorite suggestion, not your deliverable.",
    "Hi {name}! Your ceiling plan hides MEP like a secret society.",
    "Hi {name}! Black turtleneck energy: strong — constructibility energy: missing.",
    "Hi {name}! Your door swing diagram is a philosophy seminar.",
    "Hi {name}! Golden hour on the render — overcast on the job site.",
    "Hi {name}! You sketch beauty — someone else owns the waterproofing.",
    "Hi {name}! Your stair detail has more plot twists than streaming TV.",
    "Hi {name}! Design intent clear — dimension strings optional.",
    "Hi {name}! You treat charrettes like spa days for egos.",
    "Hi {name}! Your reflected ceiling plan is a magic trick — structure vanished.",
    "Hi {name}! You visit site for content — trades visit your details for revenge.",
    "Hi {name}! Your project name sounds Latin — your budget sounds nervous.",
    "Hi {name}! You hide structure in the RCP — classic architect sorcery.",
  ],
  contractor: [
    "Hi {name}! Ceiling height on paper: 14 feet — MEP measured 9'-2\" and cried.",
    "Hi {name}! Curtain wall detail is jewelry — waterproofing detail is a rumor.",
    "Hi {name}! Your stair sketch is Bauhaus — your built stair is OSHA fan fiction.",
    "Hi {name}! You detail the facade like a museum — the back-of-house is a void.",
    "Hi {name}! Design intent slide deck: 40 pages — dimension string: see model.",
    "Hi {name}! The stair moved again — the field felt it spiritually.",
    "Hi {name}! Your door hardware schedule is a novel nobody finished.",
    "Hi {name}! You want a floating stair — physics wants a meeting you'll miss.",
    "Hi {name}! Your wall section is two lines and a prayer.",
    "Hi {name}! MEP coordination happens in your ceiling plan — theoretically.",
    "Hi {name}! You VE'd the flashing — kept the render for the brochure.",
    "Hi {name}! Constructibility review on the calendar — not in your attendance.",
    "Hi {name}! Your RFI answers read like haiku that hurt.",
    "Hi {name}! Punch list says accept as design intent — industry's middle finger.",
    "Hi {name}! You love a reveal — the framer loves a wall that exists.",
    "Hi {name}! Facade meeting: glass, hope, and eventual leakage.",
    "Hi {name}! Handrail on your sculptural stair — theoretical at best.",
    "Hi {name}! You sell clarity — you deliver a scavenger hunt in PDF.",
    "Hi {name}! Your elevation is sculptural — your section is fictional.",
    "Hi {name}! IFC Friday drop — superintendent trust issues Monday.",
  ],
  nuclear: [
    "Hi {name}! You sell minimalism — your revision clouds are maximalist art.",
    "Hi {name}! Fourteen stair revisions and you still call it minimal.",
    "Hi {name}! Your sheet index is a novel — the building is a footnote.",
    "Hi {name}! Render flawless — details fan fiction — field builds fan fiction's cousin.",
    "Hi {name}! You're why the spec says architect shall review submittals.",
    "Hi {name}! Design vision on slides — constructibility in the afterlife.",
    "Hi {name}! You moved the stair — structural sent a thank-you card and an RFI.",
    "Hi {name}! Your ceiling plan is where hope goes to suffocate.",
    "Hi {name}! Value engineering the envelope — bold strategy, wet outcome.",
    "Hi {name}! You don't value engineer — you value surprise everyone.",
    "Hi {name}! Render rooftop party — life safety plan says evacuate differently.",
    "Hi {name}! You design landmarks — the budget designs reality checks.",
    "Hi {name}! Revision cloud on sheet — weather map of everyone's patience.",
    "Hi {name}! You treat door swings like ethics — geometry lost.",
    "Hi {name}! Back-of-house missing — facade ready for magazine.",
    "Hi {name}! You scheduled constructibility — you attended aesthetics.",
    "Hi {name}! Your dimension strings are see model — the model sees chaos.",
    "Hi {name}! You visit site once — your RFIs visit the superintendent daily.",
    "Hi {name}! Floating stair — lawsuit wearing black turtleneck.",
    "Hi {name}! You hid MEP in the ceiling — MEP found the ceiling anyway.",
  ],
  nsfw: [
    "Hi {name}! You design like you bill by the square foot of unresolved detail.",
    "Hi {name}! Site visit outfit costs more than the temp fence — priorities.",
    "Hi {name}! You call it design vision — ironworkers call it extra steel.",
    "Hi {name}! Your render lies confidently — your section confesses under oath.",
    "Hi {name}! Charrette was spa day — trades still in therapy.",
    "Hi {name}! You VE'd waterproofing — water found the gap and sent a thank-you.",
    "Hi {name}! Minimalism on Instagram — maximalism in the RFI log.",
    "Hi {name}! Black turtleneck immaculate — flashing detail missing in action.",
    "Hi {name}! AI's taking your job — #AI'sB#@$H and the stair still doesn't fit.",
    "Hi {name}! Design intent poetry — field reads it as a dare.",
  ],
};

/** Single-sentence mean-mode lines (share-safe profanity patterns). */
export const ARCHITECT_MEAN_LINES = [
  `{name}, your render has people partying on the roof while your section shows zero headroom — classic split personality.`,
  `{name}, you named it Nexus because substance costs extra and revision clouds are free.`,
  `{name}, your curtain wall detail is jewelry and your waterproofing detail is a rumor the field stopped believing.`,
  `{name}, you want a floating stair because physics is someone else's contract — preferably structural's.`,
  `{name}, your design intent deck is forty pages of vibe and one dimension that says see model.`,
  `{name}, you visit site once for golden hour — the superintendent visits your inbox for blood.`,
  `{name}, your ceiling plan is where MEP goes to fight for air and lose politely.`,
  `{name}, you VE'd the part that kept water out and kept the render for the brochure — priorities.`,
  `{name}, your door hardware schedule is War and Peace — Division 08 still loses.`,
  `{name}, you sell minimalism while your revision clouds qualify as weather systems.`,
  `{name}, your handrail on that sculptural stair is theoretical — OSHA is practical.`,
  `{name}, you hide structure in the reflected ceiling plan like it's a magic trick — the magician is late.`,
  `{name}, your punch list note accept as design intent is the industry's middle finger in cursive.`,
  `{name}, you scheduled constructibility review — attendance was optional and you opted out.`,
  `{name}, your facade is museum quality — your back-of-house is where souls go missing.`,
];
