import type { Intensity } from "../../types";

export const BIM_GRILL_ON = [
  "federated model divorce and shared custody of ghosts",
  "LOD slide deck vs ceiling reality",
  "Navisworks clash theater and issue ping-pong",
  "BEP promises vs trade participation fiction",
  "Copy of Copy of Revit families",
  "closing clashes without fixing roots",
  "model delivery deadlines vs design participation",
  "issue tracker as coordination substitute",
  "4D simulation poetry vs day-one site prose",
  "clash names funnier than the comedy channel",
  "timestamping chaos in 3D and calling it VDC",
  "Revit crash log as memoir",
  "coordination meeting where everyone exports wrong",
  "IFC handoff fiction",
  "view templates vs field measure truth",
  "BIM execution plan everyone signed, nobody read",
];

export const BIM_AVOID = [
  "pretty render aesthetics and black turtleneck site visits (architect)",
  "stamping structural calcs Friday (structural engineer)",
  "superintendent hammer jokes and daily sequence",
  "owner VE smile deleting facade",
  "Division 08 door hardware religion (specifier)",
  "duct sizing as engineer of record (MEP design)",
];

export const BIM_ANGLES = [
  "LOD 500 on deck — LOD 200 in the plenum.",
  "Clash report: 9,000 issues, three closed — coordination!",
  "BEP promised peace — clash matrix promised overtime.",
  "Federated model: divorce with shared custody of ghosts.",
  "You timestamp chaos in 3D — call it VDC.",
  "Navisworks session: group therapy with section boxes.",
  "Copy of Copy of Duct — family tree of regret.",
  "Issue closed — root cause still dating the architect.",
  "4D says on time — superintendent says comedy.",
  "Model delivery Friday — trades opened it Monday, cried.",
  "Clash name Pipe vs Beam of Regret — accurate journalism.",
  "You ask design to model door hardware — they model hope.",
  "Revit crashed — your career didn't, somehow.",
  "Coordination report 400 pages — solution is another meeting.",
  "LOD slide immaculate — ceiling height still a lie.",
  "You color-code blame beautifully in the matrix.",
  "BEP section 4.2 — industry folklore.",
  "Federation complete — geometry still fighting.",
  "You close clashes like inbox zero — performance art.",
  "Trade model late — your deadline early — classic.",
  "View template perfect — field photo disagrees.",
  "IFC export clean — field import cursed.",
  "You run coordination like CSI — everyone's suspect.",
  "BIM manager not designer — model still gets blamed on you.",
  "Clash tolerance adjusted — problem adjusted to tolerance.",
  "Your issue tracker screams in professional font.",
  "VDC roadmap PowerPoint — site runs on RFIs.",
  "You host panic in 3D — attendance mandatory.",
  "Model says coordinated — superintendent says cute.",
  "You don't design buildings — you babysit geometry.",
];

export const BIM_ROAST_LINES: Record<Intensity, string[]> = {
  light: [
    "Hi {name}! Your federated model is a soap opera — everyone's cheating on the origin.",
    "Hi {name}! Navisworks clashes are your social circle — loud, recurring, unresolved.",
    "Hi {name}! Your BEP is signed — reading it is optional, apparently.",
    "Hi {name}! Copy of Copy of Revit — your file naming is a cry for help.",
    "Hi {name}! You close clashes like inbox zero — satisfying, temporary, fictional.",
    "Hi {name}! Your LOD slide deck is inspirational — your ceiling LOD is inspirational too, wrong way.",
    "Hi {name}! Issue tracker green — field still red, but the font is professional.",
    "Hi {name}! You timestamp chaos in 3D and call it progress.",
    "Hi {name}! Your coordination meeting has an agenda and a body count.",
    "Hi {name}! Trade model delivery: late. Your reminder email: on time, every time.",
    "Hi {name}! Your clash names are funnier than your last vacation.",
    "Hi {name}! 4D simulation gorgeous — day one on site is prose by chaos.",
    "Hi {name}! You love a view template — reality loves a section box surprise.",
    "Hi {name}! IFC export succeeded — someone's field day just got harder.",
    "Hi {name}! Your issue ping-pong game is Olympic caliber.",
    "Hi {name}! BEP section 4.2 — industry folklore with your name on it.",
    "Hi {name}! You don't design buildings — you herd geometry with trust issues.",
    "Hi {name}! Federated model complete — divorce proceedings ongoing.",
  ],
  contractor: [
    "Hi {name}! LOD on slides vs LOD in model — a classic BIM love story.",
    "Hi {name}! Your clash report is a cry for help in 3D — 9,000 issues, three closed.",
    "Hi {name}! You host coordination like CSI — every trade is a suspect.",
    "Hi {name}! Issue closed — root cause still dating the architect.",
    "Hi {name}! Your Navisworks session is group therapy with section boxes.",
    "Hi {name}! Model delivery Friday — superintendent trust issues Monday.",
    "Hi {name}! You ask design to model door hardware — they send a box and prayers.",
    "Hi {name}! Clash tolerance adjusted — problem adjusted to match.",
    "Hi {name}! Your coordination report is 400 pages — solution is another meeting.",
    "Hi {name}! Revit crashed — your composure didn't, barely.",
    "Hi {name}! You color-code blame in the matrix — rainbow of avoidance.",
    "Hi {name}! BEP promised peace — clash matrix promised overtime.",
    "Hi {name}! Trade participation optional — your deadline mandatory.",
    "Hi {name}! You export IFC clean — field imports cursed, as tradition demands.",
    "Hi {name}! Your 4D says on schedule — the superintendent sent a meme.",
    "Hi {name}! Federated model: shared custody of ghosts and grudges.",
    "Hi {name}! You close clashes without fixing roots — gardening, not engineering.",
    "Hi {name}! VDC roadmap on PowerPoint — site runs on RFIs and spite.",
  ],
  nuclear: [
    "Hi {name}! LOD 400 on the deck, LOD 200 in the model — honest marketing.",
    "Hi {name}! You don't coordinate — you host panic in 3D with catering.",
    "Hi {name}! Your clash names are funnier than the comedy channel — Pipe vs Beam of Regret.",
    "Hi {name}! The model lied — you're still surprised, which is the real tragedy.",
    "Hi {name}! You timestamp chaos and invoice it as VDC.",
    "Hi {name}! BEP everyone signed — nobody read past the cover slide.",
    "Hi {name}! Nine thousand clashes — three closed — you call that a win.",
    "Hi {name}! Your issue tracker is screaming in columns, professionally.",
    "Hi {name}! You babysit geometry — geometry treats you like a substitute teacher.",
    "Hi {name}! Federation complete — every trade still exports wrong on purpose.",
    "Hi {name}! You don't fix coordination — you document it beautifully.",
    "Hi {name}! Model says coordinated — field says cute story.",
    "Hi {name}! Your Revit crash log could be a memoir — bestseller in BIM circles.",
    "Hi {name}! Clash closed — problem moved to sheet A-101 where it thrives.",
    "Hi {name}! You run Navisworks like a courtroom — everyone's guilty, no verdict.",
    "Hi {name}! 4D animation poetry — superintendent's daily report is the sequel.",
    "Hi {name}! You promised a single source of truth — delivered a group chat.",
    "Hi {name}! BIM manager not designer — every RFI still lands on your desk.",
  ],
  nsfw: [],
};
