import type { HatArchetypeGuide } from "./hatArchetypes";
import { ARCHITECT_ANGLES, ARCHITECT_AVOID, ARCHITECT_GRILL_ON } from "./architectVariety";
import { BIM_ANGLES, BIM_AVOID, BIM_GRILL_ON } from "./bimVariety";
import { MEP_ANGLES, MEP_AVOID, MEP_GRILL_ON } from "./mepVariety";
import { PM_ANGLES, PM_AVOID, PM_GRILL_ON } from "./pmVariety";
import { STRUCTURAL_ANGLES, STRUCTURAL_AVOID, STRUCTURAL_GRILL_ON } from "./structuralVariety";
import {
  SUPERINTENDENT_ANGLES,
  SUPERINTENDENT_AVOID,
  SUPERINTENDENT_GRILL_ON,
} from "./superintendentVariety";

/** Complete role-fidelity guides for every AECOHats.mjs profession. */
export const HAT_ARCHETYPE_GUIDES: Record<string, HatArchetypeGuide> = {
  // ─── Design consultants ───────────────────────────────────────────────────
  architect: {
    archetype:
      "Licensed design lead — owns design intent, drawings, assemblies, code-driven layout, and coordination authorship. Roast their drawings, details, aesthetics, and coordination habits — not BIM clash tickets or field hammer energy.",
    grillOn: ARCHITECT_GRILL_ON,
    avoid: ARCHITECT_AVOID,
    angles: ARCHITECT_ANGLES,
  },
  interior_designer: {
    archetype: "Interior designer — finishes, FF&E, partitions, materials, and owner taste coordination.",
    grillOn: [
      "finish schedule churn and palette indecision",
      "FF&E lead times vs opening date fiction",
      "ceiling / lighting / MEP integration gaps",
      "shop drawing vs design intent for casework",
      "owner changes after materials were ordered",
      "as-indicated finish details that indicate nothing",
    ],
    avoid: [
      "structural stamp Friday (engineer)",
      "earthwork grading and invert spots (civil)",
      "sprinkler hydraulic calcs (FP)",
      "BIM LOD slide decks",
      "superintendent mobilization stories",
    ],
    angles: [
      "Palette approved — substrate in field disagrees.",
      "FF&E lead time: six weeks or six months — yes.",
      "Finish schedule v47 — trades still guessing.",
    ],
  },
  landscape_architect: {
    archetype: "Landscape architect — site planting, hardscape, grading interface, irrigation design intent.",
    grillOn: [
      "mostly planting vs civil/utility reality",
      "irrigation design vs actual water pressure",
      "maintainability fantasy vs ops budget",
      "hardscape details vs drainage inverts",
      "specimen tree survival rate optimism",
      "landscape architect vs landscape installer blame loop",
    ],
    avoid: [
      "curtain wall deflection and mullion tolerance",
      "Revit MEP duct families",
      "superintendent RFI lifestyle",
      "Division 08 door hardware saga",
      "structural SEE STRUCTURAL bubbles",
    ],
    angles: [
      "Mostly planting — until civil says invert.",
      "Site plan gorgeous — maintenance budget isn't.",
      "Irrigation design meets reality at the backflow valve.",
    ],
  },
  lighting_designer: {
    archetype: "Lighting designer — fixture intent, controls narrative, ceiling coordination, illumination design.",
    grillOn: [
      "fixture schedule vs ACT grid reality",
      "controls narrative vs BACnet integration mess",
      "wattage / code vs owner dimming wish list",
      "coordination with ceiling height lie",
      "mockup looked great — field CRI didn't",
      "lighting consultant invited after ceiling designed",
    ],
    avoid: [
      "structural connection design",
      "grading and storm sewer design",
      "superintendent daily sequence planning",
      "buyout assumption logs",
      "sprinkler head layout as their deliverable",
    ],
    angles: [
      "Fixture schedule poetry — ceiling grid prose.",
      "Controls narrative — BMS speaks another language.",
      "Mockup glow — field installation dimmer in every sense.",
    ],
  },
  specifications_writer: {
    archetype: "Specifier — CSI sections, substitutions, product compliance, MasterFormat pain.",
    grillOn: [
      "Division 08 door hardware religion",
      "or-equal substitution trap clauses",
      "600-page spec vs one wrong sheet detail",
      "contractor shall verify as industry trauma",
      "spec vs drawing war — nobody wins",
      "product research treadmill and obsolete SKUs",
    ],
    avoid: [
      "field rough-in fights in the plenum",
      "Navisworks clash naming sessions",
      "owner iconic vision render slides",
      "ironworker pick plans",
      "AHJ field inspection pettiness as their job",
    ],
    angles: [
      "Spec is War and Peace — Division 08 still wrong.",
      "Or-equal clause: escape hatch with landscaping.",
      "Contractor shall verify — your entire personality.",
    ],
  },
  wayfinding_signage_designer: {
    archetype: "Wayfinding / signage designer — sign types, mounting, visibility, code-required egress signage.",
    grillOn: [
      "egress sign visibility vs architect aesthetic veto",
      "ADA sign specs vs installer interpretation",
      "mounting detail missing at 90% CD",
      "brand standards vs code-required copy",
      "signage package late — field paints arrows with spray paint",
      "wayfinding logic vs actual visitor confusion",
    ],
    avoid: [
      "structural load calculations",
      "HVAC equipment selection",
      "concrete flatness FF/FL",
      "buyout bid leveling",
      "clash detection issue tracker",
    ],
    angles: [
      "Wayfinding system — visitors still lost.",
      "Egress sign aesthetic fight — code won, barely.",
      "Sign mounting detail TBD — installer improvises.",
    ],
  },

  // ─── Specialty consultants ────────────────────────────────────────────────
  acoustical_consultant: {
    archetype: "Acoustical consultant — STC/NIC, room acoustics, isolation details, noise control reports.",
    grillOn: [
      "STC rating on paper vs flanking path in field",
      "200-page acoustics report vs one wall type detail",
      "invited after structure and MEP routed",
      "isolation detail nobody builds",
      "room acoustics model vs HVAC rumble reality",
      "fee burn in coordination meetings about ceiling height",
    ],
    avoid: [
      "GC master schedule float",
      "architect render people on roof",
      "rebar lap splice arguments",
      "sprinkler branch line install",
      "owner draw inspection paperwork",
    ],
    angles: [
      "STC 55 on paper — flanking path says hello.",
      "Report is a novel — detail is a shrug.",
      "Invited late — sound travels faster than your fee.",
    ],
  },
  building_envelope_consultant: {
    archetype: "Envelope consultant — WRB, air barrier, thermal, condensation, cladding transition details.",
    grillOn: [
      "air barrier continuity as rumor on sections",
      "mockup passed — field lap failed",
      "thermal bridge hand-waving at parapet",
      "condensation analysis vs contractor value-engineering",
      "cladding transition detail gaps",
      "envelope report vs one constructible detail",
    ],
    avoid: [
      "Navisworks clash matrices",
      "grading invert spot lies",
      "owner leasing suite turnover",
      "Division 08 door hardware",
      "superintendent trade sequence",
    ],
    angles: [
      "Mockup passed — water found the gap anyway.",
      "Continuity detail exists — in the report appendix.",
      "Thermal bridge: hand-waved with confidence.",
    ],
  },
  sustainability_consultant: {
    archetype: "LEED / sustainability consultant — credits, energy modeling, metering, systems alignment documentation.",
    grillOn: [
      "credit documentation treadmill",
      "energy model vs built meter performance",
      "material red list paperwork chase",
      "submittal credit forms vs field substitution",
      "WELL/LEED point math vs VE massacre",
      "commissioning overlap finger-pointing",
    ],
    avoid: [
      "superintendent daily field reports",
      "steel erection bolt-up",
      "sprinkler head layout install",
      "concrete pour sequence",
      "AHJ plan check comments as their output",
    ],
    angles: [
      "LEED Platinum on slides — Bronze in submittals.",
      "Energy model perfect — meter tells another story.",
      "Credit form filed — field substitution filed faster.",
    ],
  },
  kitchen_design_consultant: {
    archetype: "Food service / kitchen consultant — equipment, hoods, MEP rough-in coordination, FSE layouts.",
    grillOn: [
      "hood exhaust vs make-up air coordination",
      "equipment schedule vs floor drain reality",
      "MEP rough-in clash with structure discovered late",
      "health department vs design aesthetic fight",
      "stainless layout vs actual operator workflow",
      "kitchen consultant drawing vs field improvisation",
    ],
    avoid: [
      "curtain wall anchor deflection",
      "traffic study parking counts only",
      "landscape planting schedule",
      "structural seismic calcs",
      "BIM federated model standards",
    ],
    angles: [
      "Hood sized — make-up air still TBD.",
      "FSE layout pretty — health inspector has thoughts.",
      "Floor drain location: design mystery, field guess.",
    ],
  },
  security_design_consultant: {
    archetype: "Security design consultant — access control, CCTV, intrusion, door hardware integration.",
    grillOn: [
      "camera FOV vs architect soffit veto",
      "access control points vs door hardware spec war",
      "head-end room size lie on plans",
      "integration with low voltage contractor blame",
      "security report vs one riser diagram",
      "late invite — conduit pathways already poured",
    ],
    avoid: [
      "grading and stormwater design",
      "concrete flatwork finishing",
      "roofing membrane laps",
      "precon buyout spreadsheets",
      "heritage preservation material matching",
    ],
    angles: [
      "Camera sees everything — except that column.",
      "Access control integrated — in the report, not the field.",
      "Head-end room on plan — actual closet under stairs.",
    ],
  },
  av_telecom_designer: {
    archetype: "AV / telecom designer — racks, head-end, cable pathways, room technology layouts.",
    grillOn: [
      "cable pathway vs structure already poured",
      "head-end cooling vs closet size lie",
      "AV rack load on structure nobody checked",
      "room tech layout vs owner IT standards drift",
      "structured cable spec vs low-voltage installer shortcuts",
      "late pathway coordination — core drill apology tour",
    ],
    avoid: [
      "earthwork cut/fill quantities",
      "sprinkler hydraulic density calcs",
      "masonry anchor spacing",
      "superintendent lookahead",
      "owner lender draw inspection",
    ],
    angles: [
      "Pathway on drawing — core drill says otherwise.",
      "Head-end room sized for rack — not heat.",
      "Structured cable spec — installer brought zip ties.",
    ],
  },

  // ─── Engineering consultants ──────────────────────────────────────────────
  structural_engineer: {
    archetype: "Structural engineer — members, loads, foundations, lateral system, connections, stamped calcs.",
    grillOn: STRUCTURAL_GRILL_ON,
    avoid: STRUCTURAL_AVOID,
    angles: STRUCTURAL_ANGLES,
  },
  civil_engineer: {
    archetype: "Civil engineer — grading, drainage, utilities, paving, erosion control, site design.",
    grillOn: [
      "grading plan vs as-built mud",
      "storm vs sanitary pipe fiction",
      "utility conflict discovered at 3am",
      "ROW / easement surprise",
      "erosion control BMP vs rain event",
      "paving detail vs actual subgrade",
    ],
    avoid: [
      "interior ACT ceiling grid",
      "sprinkler head layout install",
      "architect render aesthetics",
      "curtain wall sealant",
      "BIM issue tracker",
    ],
    angles: [
      "Grading perfect on paper — rain disagrees.",
      "Utility conflict: scheduled for never.",
      "Storm pipe designed — sanitary pipe installed. Classic.",
    ],
  },
  geotechnical_engineer: {
    archetype: "Geotechnical engineer — soils, bearing, settlement, groundwater, excavation support recommendations.",
    grillOn: [
      "borings vs surprise at excavation",
      "bearing capacity optimism",
      "report nobody read until failure",
      "shoring recommendation vs GC cost panic",
      "settlement prediction vs tenant complaint",
      "groundwater show-up uninvited",
    ],
    avoid: [
      "curtain wall mullion design",
      "toilet partition layout",
      "BIM LOD slide deck",
      "interior paint VOC spec",
      "fire alarm device placement",
    ],
    angles: [
      "Borings said fine — excavation said plot twist.",
      "Report is thorough — field surprise is also thorough.",
      "Bearing capacity: theoretical friend, practical stranger.",
    ],
  },
  survey_engineer: {
    archetype: "Surveyor / geomatics — benchmarks, control, topo, layout basis, as-built survey.",
    grillOn: [
      "benchmark fights between trades",
      "control network vs ironworker trust issues",
      "topo vs design grading fiction",
      "as-built survey vs design model divorce",
      "layout basis changed without telling anyone",
      "survey says fine — tape measure says lawsuit",
    ],
    avoid: [
      "HVAC load calculations",
      "spec Division 08 substitutions",
      "owner program creep",
      "sprinkler branch sizing",
      "architect design intent slides",
    ],
    angles: [
      "Benchmark set — everyone measures differently anyway.",
      "Control network gospel — field uses chalk line.",
      "Topo says flat — design says terrace. Fun.",
    ],
  },
  traffic_engineer: {
    archetype: "Traffic engineer — access, circulation, parking counts, loading zones, curb cuts.",
    grillOn: [
      "parking count math vs actual tenant demand",
      "loading zone fiction vs delivery truck reality",
      "circulation diagram vs pedestrian chaos",
      "curb cut timing vs utility trench conflict",
      "traffic study assumptions vs opening day",
      "fire lane width vs landscape island",
    ],
    avoid: [
      "interior millwork alignment",
      "rebar cover arguments",
      "BMS BACnet point mapping",
      "roofing membrane warranty",
      "demolition selective sequence",
    ],
    angles: [
      "Parking count works — if nobody shops here.",
      "Loading zone designed for sprinter van — got semi.",
      "Circulation plan — pedestrians chose chaos.",
    ],
  },
  mechanical_engineer: {
    archetype: "Mechanical engineer (design) — HVAC loads, equipment selection, duct/pipe sizing, energy calcs.",
    grillOn: MEP_GRILL_ON,
    avoid: MEP_AVOID,
    angles: MEP_ANGLES,
  },
  electrical_engineer: {
    archetype: "Electrical engineer (design) — service, distribution, fault current, lighting, load calcs, one-lines.",
    grillOn: [
      "one-line diagram vs field conduit maze",
      "panel schedule vs as-built device count",
      "fault current study vs utility coordination delay",
      "lighting design vs ceiling grid fight",
      "short circuit calcs vs contractor substitution",
      "arc flash label package late",
    ],
    avoid: [
      "grading invert spots",
      "curtain wall anchor design",
      "demo abatement containment",
      "superintendent trade sequence",
      "food service hood sizing",
    ],
    angles: [
      "One-line clean — field conduit abstract art.",
      "Panel schedule v12 — field has v0.5.",
      "Fault study done — utility letter still pending.",
    ],
  },
  plumbing_engineer: {
    archetype: "Plumbing engineer (design) — fixture units, pipe sizing, venting, specialty systems.",
    grillOn: [
      "invert spot on paper vs field camera",
      "fixture schedule vs rough-in reality",
      "vent routing vs structure beam surprise",
      "domestic vs waste coordination in slab",
      "pipe sizing vs VE fixture downgrade",
      "specialty systems (med gas interface) coordination late",
    ],
    avoid: [
      "steel erection pick plans",
      "LEED credit documentation",
      "glazing deflection analysis",
      "roofing penetration flashing install",
      "owner leasing suite criteria",
    ],
    angles: [
      "Invert on plan — camera has receipts.",
      "Fixture schedule luxury — rough-in economy.",
      "Vent routing elegant — beam said no.",
    ],
  },
  fire_protection_engineer: {
    archetype: "Fire protection engineer (design) — sprinkler density, standpipe, NFPA calcs, special suppression design.",
    grillOn: [
      "sprinkler density calc vs ceiling obstruction",
      "standpipe design vs shaft size lie",
      "NFPA report vs constructible head layout",
      "special suppression spec vs contractor scope gap",
      "hydraulic calc pretty — field branch ugly",
      "coordination with architect ceiling aesthetic",
    ],
    avoid: [
      "field sprinkler install and hanger fights (sprinkler contractor)",
      "architect render aesthetics",
      "civil storm sewer",
      "BIM clash ticket hygiene",
      "owner draw inspection",
    ],
    angles: [
      "Hydraulic calc pristine — ceiling obstruction feral.",
      "Density met on paper — head layout met in dreams.",
      "NFPA is your love language — GC doesn't speak it.",
    ],
  },
  code_consultant: {
    archetype: "Code consultant — occupancy, height/area, egress, accessibility overlays, code analysis reports.",
    grillOn: [
      "occupancy classification debate as sport",
      "egress analysis vs architect stair aesthetic",
      "height/area math vs mezzanine fiction",
      "code report vs AHJ interpretation difference",
      "accessibility overlay vs value engineering",
      "invited after design locked — surprise rework",
    ],
    avoid: [
      "field installation quality inspection",
      "buyout bid tabulation",
      "duct fabrication SMACNA",
      "concrete placement curing",
      "landscape planting install",
    ],
    angles: [
      "Egress works — if you run at Olympic pace.",
      "Occupancy math — architect heard 'maybe'.",
      "Code report done — AHJ heard different code.",
    ],
  },
  vertical_transport_consultant: {
    archetype: "Vertical transportation consultant — elevator/escalator performance, pits, machine rooms, VT specs.",
    grillOn: [
      "pit depth vs structural coordination late",
      "machine room size lie on architectural plans",
      "elevator performance spec vs contractor shop drawing lag",
      "shaft dimension discovered last Tuesday",
      "escalator truss support coordination gap",
      "VT report vs one shaft section detail",
    ],
    avoid: [
      "roofing membrane warranty callback",
      "interior paint substrate prep",
      "traffic parking count study only",
      "rebar lap length arguments",
      "BMS BACnet integration",
    ],
    angles: [
      "Shaft coordinated — in a dream, last Tuesday.",
      "Machine room on plan — actual broom closet.",
      "VT spec performance — contractor schedule performance.",
    ],
  },
  commissioning_authority: {
    archetype: "CxA — systems verification, OPR/BoD alignment, functional performance testing, commissioning reports.",
    grillOn: [
      "FPT failures and retest loops",
      "OPR vs installed reality gap",
      "seasonal testing delays pushing turnover",
      "TAB follow-up finger-pointing",
      "Cx report thickness vs punch closure rate",
      "systems incomplete — Cx schedule aggressive anyway",
    ],
    avoid: [
      "earthwork compaction testing only",
      "curtain wall shop drawing fabrication",
      "architect render aesthetics",
      "demolition selective protection",
      "owner leasing turnover criteria only",
    ],
    angles: [
      "FPT failed — seasonally convenient retest scheduled.",
      "OPR aspirational — installed system realistic.",
      "Cx report thick — punch list thicker.",
    ],
  },
  environmental_consultant: {
    archetype: "Environmental consultant — Phase I/II, remediation, erosion, permitting support, contamination.",
    grillOn: [
      "Phase I surprise recommendation at bid time",
      "remediation scope creep vs schedule",
      "SWPPP vs actual erosion event",
      "contamination report vs excavation budget shock",
      "permit support delays entitlement",
      "environmental hold point vs GC acceleration plea",
    ],
    avoid: [
      "interior ACT ceiling grid level",
      "elevator guide rail tolerance",
      "lighting fixture aesthetic",
      "steel weld inspection",
      "owner iconic vision render",
    ],
    angles: [
      "Phase I clean — Phase II plot twist.",
      "SWPPP on shelf — rain on field.",
      "Remediation budget — GC's new horror genre.",
    ],
  },

  // ─── Stakeholders ─────────────────────────────────────────────────────────
  owner_representative: {
    archetype: "Owner / client representative — scope, budget, milestones, acceptance, stakeholder decisions.",
    grillOn: [
      "approval latency vs schedule fiction",
      "scope creep questions disguised as quick syncs",
      "stakeholder alignment theater",
      "acceptance criteria moving goalposts",
      "budget guardrails vs program wish list",
      "decision deferred until it's expensive",
    ],
    avoid: [
      "clash detection naming",
      "rebar placement inspection",
      "Division 08 spec writing",
      "duct rough-in in plenum",
      "stamp structural Friday",
    ],
    angles: [
      "Quick question — twelve bullets, new wing.",
      "Approval pending — industry runs on pending.",
      "Acceptance criteria — version 14 today.",
    ],
  },
  owners_project_manager: {
    archetype: "Owner's PM — client-side schedule, budget, design team wrangling, vendor coordination.",
    grillOn: PM_GRILL_ON,
    avoid: PM_AVOID,
    angles: PM_ANGLES,
  },
  lender_inspector: {
    archetype: "Lender / third-party reviewer — progress verification, quality review, draw support documentation.",
    grillOn: [
      "draw request paperwork vs actual progress",
      "progress photo staging",
      "TPR report vs field deficiency",
      "milestone verification delays funding",
      "percent complete math optimism",
      "lender hold on work that was 'done' last month",
    ],
    avoid: [
      "designing curtain wall details",
      "BIM standards enforcement",
      "HVAC load calculations",
      "landscape planting design",
      "superintendent daily trade sequence",
    ],
    angles: [
      "Percent complete: 80% — lender heard 52%.",
      "Draw package thick — progress photo thin.",
      "TPR visit — GC's performance art debut.",
    ],
  },
  leasing_property: {
    archetype: "Leasing / property management — suites, amenities, turnover criteria, tenant readiness.",
    grillOn: [
      "suite turnover criteria vs construction reality",
      "amenity promise vs VE deletion",
      "tenant fit-out coordination blame",
      "opening date marketing vs punch list",
      "common area finish vs budget strip-mall",
      "lease plan vs as-built square footage",
    ],
    avoid: [
      "structural seismic design",
      "shoring design calculations",
      "fire protection hydraulic calcs",
      "earthwork compaction",
      "AHJ plan check comments",
    ],
    angles: [
      "Turnover ready — punch list disagrees.",
      "Amenity package marketed — VE package delivered.",
      "Suite plan perfect — as-built creative.",
    ],
  },

  // ─── Regulatory ───────────────────────────────────────────────────────────
  ahj_plan_reviewer: {
    archetype: "AHJ plan reviewer — code compliance, completeness review, permit conditions, resubmittals.",
    grillOn: [
      "comment letter volume as schedule driver",
      "resubmittal cycle pettiness (professional)",
      "code interpretation hold points",
      "permit set completeness checklist",
      "plan check correction letter tone",
      "design team calls you final boss — accurately",
    ],
    avoid: [
      "Revit modeling and LOD slides",
      "buyout bid leveling",
      "field rough-in quality",
      "BEP standards writing",
      "owner program workshops",
    ],
    angles: [
      "Final boss of entitlement — undefeated.",
      "Comments read like bureaucracy breakup letter.",
      "Resubmittal 4 — still petty, still right.",
    ],
  },
  heritage_officer: {
    archetype: "Heritage / preservation reviewer — conservation, materials, reinstatement, HPO compliance.",
    grillOn: [
      "material matching requirements vs budget",
      "reinstatement detail vs contractor capability",
      "heritage hold on modern intervention",
      "conservation report vs constructible detail",
      "HPO comment letter as schedule black hole",
      "facade restoration vs VE brick substitution fight",
    ],
    avoid: [
      "HVAC duct sizing",
      "concrete pump truck logistics",
      "BMS point mapping",
      "precon buyout optimism",
      "sprinkler contractor hanger layout",
    ],
    angles: [
      "Match the heritage brick — budget matched asphalt.",
      "Reinstatement detail — contractor matched shrug.",
      "HPO approved — after revision 7.",
    ],
  },
  accessibility_reviewer: {
    archetype: "Accessibility reviewer — routes, clearances, hardware, fixtures, ADA/AODA compliance.",
    grillOn: [
      "clearance dimension vs built obstruction",
      "route continuity fiction on plans",
      "door hardware spec vs installer shortcut",
      "fixture mounting height vs field improvisation",
      "accessibility report vs one corrected detail",
      "barrier-free path blocked by 'temporary' storage",
    ],
    avoid: [
      "structural wind load calcs",
      "grading storm sewer design",
      "roofing membrane warranty",
      "steel fabrication weld procedures",
      "owner lender draw",
    ],
    angles: [
      "Barrier-free route — barrier-rich reality.",
      "Clearance on plan — column disagrees.",
      "ADA compliant — after punch list 3.",
    ],
  },

  // ─── Preconstruction ──────────────────────────────────────────────────────
  estimator: {
    archetype: "Estimator — quantities, takeoffs, pricing, alternates, allowances, bid accuracy.",
    grillOn: [
      "takeoff vs field condition surprise",
      "VE math vs reality",
      "bid spread shock at bid opening",
      "allowance fiction everyone spends through",
      "alternate pricing optimism",
      "scope gap discovered post-award",
    ],
    avoid: [
      "Navisworks clash detection",
      "site safety toolbox talk delivery",
      "architect render aesthetics",
      "commissioning FPT execution",
      "heritage material matching",
    ],
    angles: [
      "Takeoff perfect — field conditions imperfect.",
      "Allowance held — spent by Tuesday.",
      "Bid spread — estimator therapy session.",
    ],
  },
  scheduler: {
    archetype: "Scheduler / planner — CPM logic, milestones, trade flow, lookahead, recovery schedules.",
    grillOn: [
      "float that ghosted",
      "recovery schedule fiction with better fonts",
      "logic tie optimism",
      "milestone moved again — surprise zero",
      "lookahead astrology",
      "Gantt green — field citations needed",
    ],
    avoid: [
      "sprinkler hydraulic calcs",
      "curtain wall anchor design",
      "Division 08 spec writing",
      "acoustical STC testing",
      "landscape planting design",
    ],
    angles: [
      "Float left — schedule still green somehow.",
      "Recovery schedule — recovering from last recovery.",
      "Logic ties — field ties knots instead.",
    ],
  },
  procurement_contracts: {
    archetype: "Procurement / contracts — bid packages, POs, submittal logs, subcontract execution.",
    grillOn: [
      "submittal log backlog",
      "PO issued — scope still ambiguous",
      "bid package missing sheet legend",
      "contract language vs field interpretation",
      "procurement cycle vs design revision churn",
      "or-equal substitution paperwork avalanche",
    ],
    avoid: [
      "structural connection design",
      "field layout benchmark",
      "energy model inputs",
      "roofing install weather window",
      "demolition hammer energy",
    ],
    angles: [
      "PO cut — scope TBD, classic.",
      "Submittal log — horror anthology.",
      "Bid package complete — minus the details.",
    ],
  },
  preconstruction_manager: {
    archetype: "Preconstruction manager — scope packaging, trade boundaries, risk, buyout leadership.",
    grillOn: [
      "buyout spread shock",
      "assumption log fiction",
      "drawing set used for bid lies",
      "trade boundary gaps",
      "risk register optimism",
      "precon meeting where subs learn truth",
    ],
    avoid: [
      "Navisworks group therapy",
      "field layout embed tolerance",
      "AHJ comment letter pettiness as their output",
      "TAB air balance report",
      "architect site visit outfit",
    ],
    angles: [
      "Assumptions folder — industry folklore.",
      "Buyout done — surprises just beginning.",
      "Trade boundaries — more like suggestions.",
    ],
  },

  // ─── GC / field ───────────────────────────────────────────────────────────
  construction_manager: {
    archetype: "Construction manager / PM — overall delivery, RFIs, coordination, cost/time, meetings.",
    grillOn: PM_GRILL_ON,
    avoid: PM_AVOID,
    angles: PM_ANGLES,
  },
  superintendent: {
    archetype: "Superintendent / general foreman — daily sequence, trade access, logistics, field production.",
    grillOn: SUPERINTENDENT_GRILL_ON,
    avoid: SUPERINTENDENT_AVOID,
    angles: SUPERINTENDENT_ANGLES,
  },
  site_safety: {
    archetype: "Site safety — fall protection, access, hot work, logistics hazards, OSHA compliance.",
    grillOn: [
      "toolbox talk attendance fiction",
      "near-miss paperwork treadmill",
      "PPE vs summer heat reality",
      "hot work permit vs actual hot work",
      "fall protection plan vs creative scaffolding",
      "safety observation card volume vs behavior change",
    ],
    avoid: [
      "BIM LOD slide decks",
      "structural load calcs",
      "owner VE smile",
      "spec Division 08",
      "energy modeling",
    ],
    angles: [
      "Toolbox talk signed — harness still decorative.",
      "Near-miss filed — miss still near.",
      "Hot work permit — work was hotter.",
    ],
  },
  quality_control: {
    archetype: "QC/QA — ITP, hold points, inspections, NCRs, deficiency tracking, standards enforcement.",
    grillOn: [
      "NCR backlog never zero",
      "ITP vs field reality gap",
      "punch list immortality",
      "inspection hold point delays",
      "deficiency photo library growth",
      "quality plan thickness vs compliance depth",
    ],
    avoid: [
      "buyout Excel optimism",
      "architect Horizon project naming",
      "Navisworks clash matrix",
      "traffic parking study",
      "landscape design planting plan",
    ],
    angles: [
      "NCR closed — reopened by weather.",
      "ITP followed — field followed shortcuts.",
      "Punch list — immortal genre.",
    ],
  },
  layout_engineer_field: {
    archetype: "Layout / field engineer — grid, benchmark, embeds, as-built capture, survey coordination.",
    grillOn: [
      "benchmark fights between trades",
      "embed tolerance vs ironworker interpretation",
      "as-built vs design grid divorce",
      "survey vs tape measure trust issues",
      "layout point shot — design point moved",
      "as-built capture always one pour late",
    ],
    avoid: [
      "BEP standards writing",
      "owner program workshops",
      "spec or-equal traps",
      "LEED documentation",
      "heritage material approval",
    ],
    angles: [
      "Benchmark gospel — field heresy.",
      "Embed location — ironworker edition.",
      "As-built capture — always chasing the last pour.",
    ],
  },
  bim_vdc_coordinator: {
    archetype:
      "BIM/VDC coordinator — federates trade models, runs clashes, tracks issues, enforces standards. Does NOT design buildings or run the job site.",
    grillOn: BIM_GRILL_ON,
    avoid: BIM_AVOID,
    angles: BIM_ANGLES,
  },

  // ─── Structural & site trades ─────────────────────────────────────────────
  excavation_earthwork: {
    archetype: "Excavation / earthwork contractor — cuts, fills, compaction, haul routes, mass grading.",
    grillOn: [
      "cut/fill quantity vs survey surprise",
      "compaction test failures and rework",
      "haul route vs neighbor complaint",
      "geotech report vs actual soil",
      "over-excavation and backfill drama",
      "rain event vs slope stability",
    ],
    avoid: [
      "Division 08 door hardware",
      "BIM execution plans",
      "architect render aesthetics",
      "LEED credit forms",
      "elevator pit rail alignment",
    ],
    angles: [
      "Geotech said clay — field said soup.",
      "Compaction test — third time's charm.",
      "Haul route optimized — neighbor optimized complaint.",
    ],
  },
  shoring_underpinning: {
    archetype: "Shoring / underpinning contractor — soldier pile, lagging, rakers, tiebacks, dewatering interface.",
    grillOn: [
      "shoring design vs utility surprise",
      "dewatering permit vs actual water table",
      "tieback testing delays excavation",
      "lagging vs unexpected obstructions",
      "underpinning sequence vs neighbor vibration fear",
      "geotech recommendation vs field conditions",
    ],
    avoid: [
      "interior paint VOC compliance",
      "lighting fixture schedule",
      "owner leasing suite plan",
      "spec or-equal substitution",
      "BMS BACnet mapping",
    ],
    angles: [
      "Shoring designed — groundwater redesigned the plan.",
      "Tieback test — neighbor's crystal vase test.",
      "Underpinning sequence — neighbor's anxiety sequence.",
    ],
  },
  piling_deep_foundations: {
    archetype: "Piling / deep foundations contractor — piles, caissons, drilling, tolerances, load tests.",
    grillOn: [
      "pile capacity test vs schedule",
      "drilling obstructions and overruns",
      "caisson slurry vs neighbor complaints",
      "tolerance fights with survey",
      "geotech bearing vs actual refusal",
      "pile cut-off elevation surprises",
    ],
    avoid: [
      "curtain wall sealant",
      "ACT ceiling grid",
      "architect design intent slides",
      "procurement PO backlog",
      "heritage brick matching",
    ],
    angles: [
      "Bearing capacity met — on the test pile only.",
      "Drilling obstructions — free plot twists.",
      "Cut-off elevation — survey's favorite debate.",
    ],
  },
  formwork_contractor: {
    archetype: "Formwork contractor — forming, pour sequence, anchor bolts, embeds, concrete interface.",
    grillOn: [
      "pour sequence vs design radius change",
      "anchor bolt template fights",
      "embed coordination misses",
      "formwork oil vs architect finish complaint",
      "pour card weather roulette",
      "formwork reuse vs architect curve ambition",
    ],
    avoid: [
      "HVAC load calculations",
      "traffic study parking counts",
      "fire alarm device layout design",
      "owner program workshop",
      "LEED submittal forms",
    ],
    angles: [
      "Pour sequence planned — design changed radius.",
      "Anchor bolt template — ironworker abstract art.",
      "Formwork for that curve — architect's sculpture fee.",
    ],
  },
  rebar_contractor: {
    archetype: "Reinforcing steel contractor — rebar laps, chairs, couplers, cover, placing drawings.",
    grillOn: [
      "lap splice vs structural detail ambiguity",
      "cover tolerance vs architect finish complaint",
      "coupler substitution fights",
      "rebar congestion at intersections",
      "placing drawing vs field improvisation",
      "chair spacing vs pump hose path",
    ],
    avoid: [
      "energy model inputs",
      "wayfinding signage design",
      "lender draw inspection",
      "landscape irrigation design",
      "AV head-end cooling",
    ],
    angles: [
      "Lap length on drawing — field lap length creative.",
      "Cover maintained — architect maintained concern.",
      "Congestion at intersection — traffic worse than highway.",
    ],
  },
  concrete_placement: {
    archetype: "Concrete placement / finisher — slabs, walls, joints, flatness FF/FL, curing.",
    grillOn: [
      "FF/FL spec vs actual moon surface",
      "joint layout vs sawcut timing",
      "curing compound vs schedule acceleration",
      "hot/cold weather pour drama",
      "architect radius vs flatwork reality",
      "pour cancelled — design still revising",
    ],
    avoid: [
      "sprinkler hydraulic density design",
      "spec Division 08",
      "BIM clash naming",
      "owner iconic vision",
      "geotech report writing",
    ],
    angles: [
      "FF/FL specified — moonscape delivered.",
      "Pour scheduled — design scheduled revision instead.",
      "Joint layout art — sawcut timing comedy.",
    ],
  },
  structural_steel_fabricator: {
    archetype: "Structural steel fabricator — shop drawings, cuts, welds, shipping marks, fabrication QA.",
    grillOn: [
      "shop drawing approval lag",
      "weld symbol vs field interpretation",
      "shipping mark chaos at site",
      "fabrication tolerance vs erection surprise",
      "RFI on connection detail ambiguity",
      "steel detailer vs structural engineer SEE loop",
    ],
    avoid: [
      "site grading drainage",
      "interior paint prep",
      "owner leasing turnover",
      "AHJ plan check",
      "kitchen hood exhaust design",
    ],
    angles: [
      "Shop drawing approved — after steel needed on site.",
      "Shipping marks — erector's scavenger hunt.",
      "Weld symbol clear — field weld creative.",
    ],
  },
  structural_steel_erector: {
    archetype: "Structural steel erector — pick plans, connections, bolt-up, decking, ironworker field work.",
    grillOn: [
      "pick plan vs crane wind hold",
      "connection bolt-up vs hole alignment",
      "decking attachment vs design change",
      "ironworker vs survey trust issues",
      "waiting on engineered connection detail",
      "field weld vs shop weld scope fight",
    ],
    avoid: [
      "writing structural calcs",
      "LEED credit documentation",
      "landscape planting plan",
      "procurement bid package",
      "acoustical STC report",
    ],
    angles: [
      "Pick plan solid — wind said no picks today.",
      "Bolt-up smooth — holes disagreed.",
      "Waiting on connection detail — ironworker meditation.",
    ],
  },
  precast_erector: {
    archetype: "Precast erector — panel bracing, connections, grouting, erection sequence, tolerance.",
    grillOn: [
      "panel bracing vs wind event",
      "connection grout vs tolerance stack-up",
      "erection sequence vs crane availability",
      "architect panel aesthetic vs field chip",
      "bearing pad shim folklore",
      "precast shop drawing lag",
    ],
    avoid: [
      "HVAC duct routing design",
      "traffic engineer parking math",
      "security camera FOV design",
      "owner draw paperwork",
      "specifier or-equal clause writing",
    ],
    angles: [
      "Bracing engineered — wind improvised.",
      "Tolerance stack-up — Jenga with consequences.",
      "Panel pristine in yard — chip at erection.",
    ],
  },
  mass_timber: {
    archetype: "Mass timber / wood systems contractor — CLT, glulam, connectors, tolerances, prefab erection.",
    grillOn: [
      "connector detail vs fabricator capability",
      "CLT panel camber vs bearing surprise",
      "moisture protection during erection",
      "architect timber aesthetic vs fire rating reality",
      "tolerance vs steel connection interface",
      "prefab sequence vs site access",
    ],
    avoid: [
      "sprinkler branch layout design",
      "civil storm sewer invert",
      "elevator machine room size",
      "lender progress photos",
      "heritage HPO comments",
    ],
    angles: [
      "CLT camber — bearing said surprise.",
      "Timber beautiful — connector detail TBD.",
      "Moisture protection plan — rain had other plans.",
    ],
  },
  masonry_contractor: {
    archetype: "Masonry contractor — CMU, brick, stone, anchors, movement joints, veneer ties.",
    grillOn: [
      "movement joint location vs architect aesthetic",
      "anchor spacing vs wind load detail ambiguity",
      "mortar color match vs batch variation",
      "lintel bearing vs surprise openings",
      "cold weather mortar drama",
      "stone veneer vs WRB continuity",
    ],
    avoid: [
      "BIM LOD standards",
      "energy model calibration",
      "owner program definition",
      "TAB air balance report",
      "demolition hazmat abatement plan writing",
    ],
    angles: [
      "Movement joint hidden — cracks not hidden.",
      "Anchor detail clear — wind load unclear.",
      "Mortar color matched — batch disagreed.",
    ],
  },
  waterproofing_below_grade: {
    archetype: "Below-grade waterproofing contractor — membranes, drainage board, protection course, continuity.",
    grillOn: [
      "membrane continuity vs puncture damage",
      "drainage board vs backfill rock",
      "protection board skipped — surprise leaks",
      "water test failure finger-pointing",
      "coordination with shoring/dewatering",
      "below-grade detail vs utility penetration",
    ],
    avoid: [
      "interior ACT ceiling",
      "lighting controls narrative",
      "scheduler CPM logic",
      "architect render people on roof",
      "food service equipment schedule",
    ],
    angles: [
      "Membrane continuous — punctures discontinuous.",
      "Water test failed — blame test, not membrane.",
      "Protection board value-engineered — leaks not.",
    ],
  },

  // ─── Envelope trades ──────────────────────────────────────────────────────
  roofing_contractor: {
    archetype: "Roofing contractor — insulation, membrane, flashings, penetrations, weather windows.",
    grillOn: [
      "flashing integration at penetrations",
      "membrane warranty vs installation shortcut",
      "weather window vs schedule acceleration",
      "callback leak investigation",
      "parapet coping detail vs field lap",
      "roof drain coordination vs ponding",
    ],
    avoid: [
      "Navisworks clash sessions",
      "owner rep approval latency",
      "traffic study only",
      "structural wind calcs",
      "BMS BACnet points",
    ],
    angles: [
      "Warranty registered — leak also registered.",
      "Weather window — schedule heard 'push'.",
      "Flashing detail jewelry — field lap cry.",
    ],
  },
  sheet_metal: {
    archetype: "Architectural sheet metal — copings, gutters, metal flashings, trim, custom metalwork.",
    grillOn: [
      "coping detail vs wind uplift reality",
      "gutter slope vs architectural line",
      "custom metal lag vs shop capacity",
      "sealant compatibility assumptions",
      "coordination with roofing membrane",
      "field measurement vs shop drawing",
    ],
    avoid: [
      "geotech bearing capacity",
      "med gas piping install",
      "scheduler milestone logic",
      "code occupancy calc",
      "interior FF&E schedule",
    ],
    angles: [
      "Coping profile sleek — wind uplift nervous.",
      "Shop drawing lag — rust doesn't lag.",
      "Gutter slope — architect slope different.",
    ],
  },
  cladding_contractor: {
    archetype: "Cladding / rainscreen contractor — panels, clips, cavity, fire blocking at perimeter.",
    grillOn: [
      "clip spacing vs wind load detail",
      "cavity fire blocking continuity",
      "panel alignment vs substrate out of plane",
      "rainscreen drainage path blocked",
      "shop drawing lag vs enclosure schedule",
      "thermal clip vs energy model assumption",
    ],
    avoid: [
      "HVAC equipment selection",
      "civil utility trenching only",
      "owner lender inspection",
      "acoustical NIC testing",
      "demolition sequencing plan writing",
    ],
    angles: [
      "Rainscreen cavity — moisture's favorite hallway.",
      "Clip detail engineered — substrate unengineered.",
      "Panel alignment perfect — plane wasn't.",
    ],
  },
  glazing_curtainwall: {
    archetype: "Glazing / curtain wall contractor — anchors, mullions, glass, sealants, deflection.",
    grillOn: [
      "anchor deflection vs structural estimate",
      "sealant continuity vs rushed install",
      "shop drawing lag vs enclosure milestone",
      "mullion tolerance stack-up",
      "glass delivery vs crane schedule",
      "water test failure at mockup vs field",
    ],
    avoid: [
      "grading invert design",
      "med gas rough-in",
      "scheduler float analysis",
      "heritage material approval",
      "kitchen hood exhaust",
    ],
    angles: [
      "Deflection allowed — glass disagreed.",
      "Mockup passed — field sealant failed.",
      "Shop drawing approved — glass still on a boat.",
    ],
  },
  windows_doors_exterior: {
    archetype: "Exterior windows & doors installer — rough openings, subsills, WRB integration, storefront.",
    grillOn: [
      "rough opening size vs actual framing",
      "subsill flashing continuity",
      "WRB integration vs water intrusion",
      "storefront alignment vs slab edge",
      "hardware adjustment vs frame warp",
      "air/water test failure blame",
    ],
    avoid: [
      "structural lateral system design",
      "traffic circulation study",
      "BIM BEP writing",
      "owner program workshop",
      "sprinkler hydraulic calc",
    ],
    angles: [
      "Rough opening correct — framing incorrect.",
      "Subsill flashed — water found another door.",
      "Storefront plumb — slab edge abstract.",
    ],
  },
  air_barrier_insulation: {
    archetype: "Air barrier & insulation contractor — continuous air barrier, cavity insulation, continuity details.",
    grillOn: [
      "air barrier continuity gaps at transitions",
      "cavity insulation compression",
      "blower door test failure",
      "coordination with cladding trades",
      "thermal bridge at clip penetration",
      "insulation R-value vs installed thickness",
    ],
    avoid: [
      "elevator pit depth design",
      "rebar lap tables",
      "procurement PO terms",
      "architect render naming",
      "fire alarm FACP programming only",
    ],
    angles: [
      "Continuous air barrier — discontinuous reality.",
      "Blower door failed — door wasn't the problem.",
      "R-value on spec — compressed at cavity.",
    ],
  },
  firestopping_contractor: {
    archetype: "Firestopping / smoke seal contractor — penetrations, joints, perimeter fire containment, UL systems.",
    grillOn: [
      "through-penetration firestop vs MEP churn",
      "joint firestop vs movement",
      "UL system vs field improvisation",
      "smoke seal continuity at perimeter",
      "firestop inspection failure photos",
      "penetration added after firestop 'complete'",
    ],
    avoid: [
      "landscape planting schedule",
      "civil grading design",
      "owner budget approval",
      "structural connection calc",
      "lighting fixture aesthetic",
    ],
    angles: [
      "Firestop complete — MEP added three pipes.",
      "UL system specified — field system improvised.",
      "Smoke seal continuous — on the report.",
    ],
  },

  // ─── Interior trades ──────────────────────────────────────────────────────
  rough_carpentry_framing: {
    archetype: "Rough carpentry / framing — studs, blocking, backing, openings, structural rough work.",
    grillOn: [
      "blocking backing missing on drawings",
      "stud layout vs MEP sleeve explosion",
      "opening size vs actual door frame",
      "fire-rated assembly vs shortcut",
      "backing for casework vs forgotten",
      "framing vs design radius change",
    ],
    avoid: [
      "structural SEE notes writing",
      "AHJ plan check comments",
      "LEED credit submittals",
      "buyout assumption log",
      "energy model calibration",
    ],
    angles: [
      "Blocking on drawing — not in wall.",
      "Opening sized — door frame sized differently.",
      "Fire assembly detailed — field assembly creative.",
    ],
  },
  drywall_ceiling: {
    archetype: "Drywall / acoustical ceilings — board, finishes, ACT grid, penetrations, ceiling height reality.",
    grillOn: [
      "ceiling height lie discovered at grid",
      "ACT grid level — plenum wasn't",
      "MEP penetrations through board",
      "finish level 5 vs budget level 3",
      "soffit framing vs duct reality",
      "acoustical tile vs HVAC rumble",
    ],
    avoid: [
      "structural foundation design",
      "civil storm sewer",
      "owner lender draw",
      "BIM federated model",
      "food service hood design",
    ],
    angles: [
      "Ceiling grid level — ceiling height wasn't.",
      "Level 5 finish — budget level 'sure'.",
      "Plenum fought back — drywall lost.",
    ],
  },
  flooring_contractor: {
    archetype: "Flooring contractor — substrate, moisture, transitions, tile/carpet/epoxy/VCT installation.",
    grillOn: [
      "substrate flatness vs moisture failure",
      "transition detail vs wheelchair reality",
      "adhesive open time vs schedule push",
      "tile lippage vs architect aesthetic",
      "epoxy cure vs tenant move-in date",
      "floor prep vs previous trade damage",
    ],
    avoid: [
      "structural wind load",
      "sprinkler hydraulic design",
      "traffic engineer study",
      "specifier MasterFormat research",
      "commissioning OPR writing",
    ],
    angles: [
      "Substrate ready — moisture disagreed.",
      "Transition detail smooth — wheelchair disagreed.",
      "Epoxy curing — tenant not curing patience.",
    ],
  },
  millwork_casework: {
    archetype: "Millwork / casework installer — shop-built units, alignment, MEP integration, joinery.",
    grillOn: [
      "shop drawing vs field out-of-plumb",
      "casework alignment vs uneven floor",
      "MEP rough behind millwork surprise",
      "finish match vs batch variation",
      "anchor to backing that doesn't exist",
      "owner change after shop fab started",
    ],
    avoid: [
      "earthwork compaction test",
      "fire protection density calc",
      "scheduler logic ties",
      "geotech report",
      "elevator rail plumb",
    ],
    angles: [
      "Shop built perfect — wall built abstract.",
      "Backing specified — framing forgot.",
      "Finish matched — batch didn't.",
    ],
  },
  painting_wallcovering: {
    archetype: "Painting & wallcovering — substrate prep, finishes, coatings, VOC compliance.",
    grillOn: [
      "substrate prep vs previous trade sins",
      "VOC compliance vs schedule acceleration",
      "wallcovering pattern match vs wall out of square",
      "touch-up visibility under critical light",
      "primer vs moisture coming through",
      "color approval vs batch variation",
    ],
    avoid: [
      "structural connection design",
      "utility trench bedding",
      "BMS integration",
      "owner program definition",
      "shoring design",
    ],
    angles: [
      "Substrate prep done — sins still visible.",
      "Color approved — batch had other ideas.",
      "Critical light — painter's critical moment.",
    ],
  },
  toilet_accessories_specialties: {
    archetype: "Toilet partitions & specialties — partitions, accessories, lockers, cubicles, Division 10 install.",
    grillOn: [
      "partition layout vs actual tile layout",
      "accessory blocking missing",
      "locker alignment vs sloping floor",
      "ADA mounting height vs field shortcut",
      "lead time vs punch list pressure",
      "anchor into hollow partition — classic",
    ],
    avoid: [
      "HVAC load calc",
      "civil grading plan",
      "structural stamp",
      "BIM clash matrix",
      "environmental Phase II report writing",
    ],
    angles: [
      "Partition layout — tile layout different language.",
      "Blocking for accessories — mythical creature.",
      "ADA height — tape measure optional.",
    ],
  },
  prefab_wall_panel_shop: {
    archetype: "Prefab wall / panel shop — panel fabrication, QA, labels, shipping, modular production.",
    grillOn: [
      "panel QA vs field damage on delivery",
      "labeling vs erector confusion",
      "shipping schedule vs site readiness",
      "tolerance vs connection detail gap",
      "MEP rough in panel vs field connection",
      "modular promise vs site improvisation",
    ],
    avoid: [
      "AHJ plan review comments",
      "owner leasing criteria",
      "traffic study",
      "geotech bearing",
      "architect render aesthetics only",
    ],
    angles: [
      "Panel labeled — erector labeled confused.",
      "QA passed — delivery failed.",
      "Modular solution — site problem classic.",
    ],
  },

  // ─── MEP trades ───────────────────────────────────────────────────────────
  plumbing_mechanical_contractor: {
    archetype: "Plumbing contractor — rough-in, fixtures, trim, domestic/waste, equipment connections.",
    grillOn: [
      "rough-in invert fights with structure",
      "fixture trim delays vs opening",
      "domestic vs waste coordination in slab",
      "submittal or-equal vs engineer rejection",
      "core drill apology tour",
      "pressure test failure drama",
    ],
    avoid: [
      "steel fabrication shop drawings",
      "LEED credit documentation",
      "BIM BEP authorship",
      "architect render naming",
      "lender draw inspection",
    ],
    angles: [
      "Invert on drawing — camera on site.",
      "Trim scheduled — fixtures in another timeline.",
      "Pressure test — drama genre.",
    ],
  },
  hvac_mechanical_contractor: {
    archetype: "HVAC / mechanical contractor — equipment, duct, pipe, hangers, rigging, startup.",
    grillOn: [
      "duct in plenum vs structural beam",
      "equipment rigging vs roof curb reality",
      "hanger fights with structure",
      "TAB handoff finger-pointing",
      "equipment submittal vs engineer rejection",
      "startup failures before turnover",
    ],
    avoid: [
      "writing mechanical load calcs",
      "owner iconic vision slides",
      "heritage preservation review",
      "civil utility design",
      "spec Division 08 authorship",
    ],
    angles: [
      "Duct routed — structure un-routed.",
      "Equipment fits — curb doesn't.",
      "Startup failed — seasonally convenient.",
    ],
  },
  sheet_metal_hvac: {
    archetype: "Sheet metal duct fabrication & install — duct routing, SMACNA, connections, access doors.",
    grillOn: [
      "duct routing vs plenum reality",
      "SMACNA vs field shortcut",
      "access door where nobody can reach",
      "duct leakage test failure",
      "coordination with sprinkler heads",
      "fabrication lag vs rough-in schedule",
    ],
    avoid: [
      "structural lateral design",
      "landscape irrigation design",
      "owner program workshop",
      "code occupancy analysis",
      "environmental remediation design",
    ],
    angles: [
      "Duct designed — plenum redesigned it.",
      "Access door placed — human access optional.",
      "Leakage test — duct leaked narrative.",
    ],
  },
  piping_mechanical: {
    archetype: "Mechanical piping contractor — hydronic, refrigerant, condenser water, valves, insulation.",
    grillOn: [
      "hydronic balance vs air in system",
      "refrigerant line routing vs structure",
      "valve access behind finished ceiling",
      "pipe insulation vs condensation stain",
      "condenser water leak at coupling",
      "coordination with electrical conduit",
    ],
    avoid: [
      "architect facade design",
      "traffic parking counts",
      "heritage brick approval",
      "BIM LOD deck",
      "demolition hazmat plan writing",
    ],
    angles: [
      "Hydronic balanced — air unbalanced.",
      "Valve accessible — in theory, behind drywall.",
      "Insulation continuous — condensation decorative.",
    ],
  },
  electrical_contractor: {
    archetype: "Electrical contractor — conduit, cable, panels, devices, lighting install, rough and trim.",
    grillOn: [
      "conduit maze vs one-line simplicity",
      "panel fit in room size lie",
      "rough-in vs ceiling grid conflict",
      "device count vs as-built surprise",
      "temporary power plan drama",
      "lighting trim vs controls integration",
    ],
    avoid: [
      "civil storm pipe design",
      "architect render aesthetics",
      "geotech report authorship",
      "precon buyout",
      "sprinkler hydraulic design",
    ],
    angles: [
      "One-line elegant — conduit abstract.",
      "Panel fits — room doesn't.",
      "Temp power — permanent drama.",
    ],
  },
  medical_gas_plumbing: {
    archetype: "Medical gas / specialty plumbing — med gas, lab waste, interceptors, certification.",
    grillOn: [
      "med gas certification test failure",
      "lab waste interceptor access",
      "specialty piping vs ceiling congestion",
      "valve zone labeling vs installer shortcut",
      "AHJ inspection hold on med gas",
      "coordination with equipment vendor",
    ],
    avoid: [
      "landscape planting",
      "roofing membrane",
      "scheduler CPM",
      "architect stair aesthetic",
      "steel erection pick plan",
    ],
    angles: [
      "Med gas certified — after third test.",
      "Interceptor accessible — if you remove the ceiling.",
      "Lab waste routed — regret also routed.",
    ],
  },
  controls_bms: {
    archetype: "Controls / building automation contractor — BMS, BACnet, points, integration, sequences.",
    grillOn: [
      "BACnet integration vs proprietary lock-in",
      "points list vs actual device count",
      "sequence of operations vs installed reality",
      "graphics pretty — sensors wrong",
      "integration blame between trades",
      "commissioning finger-pointing at controls",
    ],
    avoid: [
      "GC master schedule ownership",
      "architect render naming",
      "rebar placing drawings",
      "earthwork cut/fill",
      "heritage facade restoration",
    ],
    angles: [
      "Points mapped — building unmapped.",
      "Sequence perfect — equipment improvises.",
      "BACnet open — vendor closed.",
    ],
  },
  tab_contractor: {
    archetype: "TAB contractor — testing, adjusting, balancing air/water, reports, commissioning support.",
    grillOn: [
      "air balance report vs owner complaint",
      "hydronic balance vs air in lines",
      "TAB report truth — coordination was fiction",
      "retest loops after design change",
      "access door blocked for balance",
      "VAV box settings vs occupancy reality",
    ],
    avoid: [
      "structural design",
      "landscape design",
      "owner leasing",
      "spec writing",
      "demolition planning",
    ],
    angles: [
      "TAB report honest — design wasn't.",
      "Balanced on paper — tenant disagrees.",
      "Retest scheduled — design changed again.",
    ],
  },
  low_voltage_contractor: {
    archetype: "Low voltage / structured cable contractor — data, fiber, pathways, racks, terminations.",
    grillOn: [
      "pathway vs concrete already poured",
      "fiber test failure at termination",
      "rack cable management vs chaos",
      "pathway shared with electrical interference",
      "as-built pathway vs design fiction",
      "late integration with AV/security",
    ],
    avoid: [
      "HVAC duct sizing",
      "concrete flatness FF/FL",
      "grading drainage",
      "structural stamp",
      "owner budget VE",
    ],
    angles: [
      "Pathway on plan — core drill memories.",
      "Fiber tested — termination failed poetry.",
      "Rack organized — cable spaghetti sequel.",
    ],
  },
  fire_alarm_contractor: {
    archetype: "Fire alarm / life safety systems contractor — FACP, devices, strobes, integration, testing.",
    grillOn: [
      "device placement vs ceiling aesthetic veto",
      "FACP programming vs as-built device count",
      "strobe coverage gap at inspection",
      "integration with elevator recall",
      "fire alarm test failure at AHJ",
      "device added after ceiling closed",
    ],
    avoid: [
      "structural calcs",
      "landscape irrigation",
      "buyout Excel",
      "architect render",
      "geotech borings",
    ],
    angles: [
      "Coverage complete — on drawing.",
      "FACP programmed — field devices surprise.",
      "Ceiling closed — detector location TBD.",
    ],
  },
  ev_charging_installer: {
    archetype: "EV charging / specialty electrical — EVSE, load management, feeders, panel upgrades.",
    grillOn: [
      "panel capacity vs EV load fantasy",
      "load management vs owner plug-everything wish",
      "feeder routing vs trenching surprise",
      "EVSE lead time vs opening date",
      "utility service upgrade delay",
      "charger count vs parking layout reality",
    ],
    avoid: [
      "sprinkler head layout",
      "masonry veneer ties",
      "acoustical STC",
      "heritage review",
      "kitchen hood exhaust",
    ],
    angles: [
      "Chargers specified — panel said no.",
      "Load managed — owner unmanaged.",
      "EVSE on site — utility letter in transit.",
    ],
  },

  // ─── Fire protection trades ─────────────────────────────────────────────────
  sprinkler_contractor: {
    archetype: "Fire sprinkler contractor — heads, branch lines, hangers, NFPA 13 install, inspections.",
    grillOn: [
      "head layout vs ceiling obstruction",
      "hanger fights with duct and structure",
      "branch line routing vs architect soffit",
      "hydraulic calc met — field layout didn't",
      "access panel joke for valve",
      "AHJ inspection smile at coverage gap",
    ],
    avoid: [
      "landscape planting schedule",
      "BIM LOD deck authorship",
      "owner leasing negotiations",
      "traffic study",
      "structural lateral calcs",
    ],
    angles: [
      "Head layout art — ceiling obstruction comedy.",
      "Hydraulics work — ceiling doesn't.",
      "AHJ smiling. Dangerously.",
    ],
  },
  standpipe_firehose_contractor: {
    archetype: "Standpipe / fire hose systems contractor — risers, hose valves, cabinets, hydrostatic test.",
    grillOn: [
      "riser routing vs shaft size lie",
      "hose valve cabinet depth vs wall thickness",
      "hydrostatic test failure",
      "coordination with stair pressurization",
      "fire department connection access blocked",
      "standpipe freeze protection in climate surprise",
    ],
    avoid: [
      "interior paint VOC",
      "landscape sod install",
      "scheduler float",
      "architect render",
      "food service design",
    ],
    angles: [
      "Riser fits shaft — shaft didn't exist.",
      "Hydrostatic test — drama at pressure.",
      "FDC accessible — if you move the dumpster.",
    ],
  },
  special_suppression: {
    archetype: "Special hazard / clean agent suppression — FM-200, foam, CO2, special hazard design install.",
    grillOn: [
      "clean agent discharge vs room integrity",
      "special hazard spec vs contractor scope gap",
      "integration with fire alarm abort",
      "room integrity test failure",
      "agent refill cost vs owner sticker shock",
      "coordination in data center / kitchen hood interface",
    ],
    avoid: [
      "standard sprinkler head layout only tropes",
      "civil grading",
      "millwork alignment",
      "owner draw inspection",
      "wayfinding signage",
    ],
    angles: [
      "Room integrity tested — room failed integrity.",
      "Clean agent discharged — budget also discharged.",
      "Special hazard — specially complicated.",
    ],
  },

  // ─── Conveyance ───────────────────────────────────────────────────────────
  elevator_contractor: {
    archetype: "Elevator / lift contractor — rails, doors, pits, machine room, hoistway, startup.",
    grillOn: [
      "pit depth vs as-built surprise",
      "guide rail plumb vs shaft out of plumb",
      "door alignment vs frame warp",
      "machine room cooling vs size lie",
      "startup failures before inspection",
      "shop drawing lag vs shaft ready",
    ],
    avoid: [
      "roofing membrane laps",
      "civil invert design",
      "spec Division 08 writing",
      "BIM clash naming",
      "superintendent daily report",
    ],
    angles: [
      "Shaft ready — elevator not ready.",
      "Pit depth — architect's rounding error.",
      "Rail plumb — shaft abstract art.",
    ],
  },
  escalator_contractor: {
    archetype: "Escalator / moving walk contractor — truss, supports, clearances, alignment.",
    grillOn: [
      "truss support coordination late",
      "clearance vs architectural opening",
      "alignment vs floor level mismatch",
      "startup vibration vs structural estimate",
      "shop drawing vs field opening",
      "public opening date vs escalator inspection",
    ],
    avoid: [
      "sprinkler branch design",
      "geotech report",
      "owner program",
      "landscape planting",
      "structural stamp Friday",
    ],
    angles: [
      "Truss supported — in the report.",
      "Clearance met — if passengers thin.",
      "Opening day — escalator still commissioning.",
    ],
  },

  // ─── Site & civil trades ──────────────────────────────────────────────────
  utilities_earthwork_site: {
    archetype: "Site utilities contractor — water, sewer, storm, trenching, bedding, testing.",
    grillOn: [
      "utility conflict at 3am",
      "bedding vs native material surprise",
      "pressure test failure",
      "trench safety vs schedule push",
      "invert spot lie — camera receipts",
      "as-built utility vs design fiction",
    ],
    avoid: [
      "interior millwork",
      "fire alarm FACP",
      "architect render",
      "BIM standards",
      "LEED submittal forms",
    ],
    angles: [
      "Invert spot lied — camera didn't.",
      "Utility conflict — scheduled for 3am.",
      "Pressure test — third time's charm.",
    ],
  },
  paving_asphalt_concrete: {
    archetype: "Paving contractor — subgrade, base, asphalt/concrete pavement, joints, compaction.",
    grillOn: [
      "subgrade failure under pavement",
      "joint layout vs thermal movement",
      "compaction test vs rain event",
      "pavement thickness vs truck traffic reality",
      "striping vs actual parking layout",
      "base course vs mud surprise",
    ],
    avoid: [
      "curtain wall deflection",
      "med gas certification",
      "specifier or-equal",
      "elevator rail plumb",
      "acoustical STC",
    ],
    angles: [
      "Subgrade ready — mud disagreed.",
      "Pavement designed for cars — got semis.",
      "Compaction test — rain event DLC.",
    ],
  },
  landscape_install: {
    archetype: "Landscape installation contractor — soil, planting, edging, mulch, site softscape install.",
    grillOn: [
      "planting vs soil quality reality",
      "specimen tree survival optimism",
      "irrigation stub vs actual connection",
      "mulch vs weed explosion",
      "landscape architect plan vs maintenance budget",
      "grading handoff vs ponding",
    ],
    avoid: [
      "structural steel erection",
      "fire protection hydraulic design",
      "BMS BACnet",
      "owner lender draw",
      "code egress analysis",
    ],
    angles: [
      "Mostly planting — soil mostly clay.",
      "Specimen tree — specimen dead.",
      "Landscape plan pretty — maintenance isn't.",
    ],
  },
  irrigation_contractor: {
    archetype: "Irrigation contractor — lines, heads, controllers, backflow, landscape water systems.",
    grillOn: [
      "backflow test failure",
      "controller programming vs owner override",
      "head coverage vs wind reality",
      "line break during paving",
      "pressure vs landscape architect fantasy",
      "winterization vs freeze surprise",
    ],
    avoid: [
      "curtain wall anchors",
      "structural calcs",
      "AHJ plan check",
      "precon buyout",
      "interior ACT grid",
    ],
    angles: [
      "Coverage uniform — wind non-uniform.",
      "Backflow tested — failed poetry.",
      "Controller smart — owner smarter at override.",
    ],
  },
  site_lighting_electrical: {
    archetype: "Site electrical / site lighting — poles, duct banks, site power, photo controls.",
    grillOn: [
      "pole foundation vs rock surprise",
      "duct bank routing vs utility conflict",
      "photo control vs tenant light trespass",
      "site power vs utility service delay",
      "fixture aim vs parking layout change",
      "handhole flooded — classic",
    ],
    avoid: [
      "interior lighting design aesthetic",
      "HVAC load calc",
      "millwork shop drawing",
      "heritage facade",
      "demolition hazmat",
    ],
    angles: [
      "Pole base designed — rock redesigned.",
      "Duct bank routed — utility was there first.",
      "Photo control — neighbors' bedroom control.",
    ],
  },
  fencing_site_amenities: {
    archetype: "Fencing / site amenities installer — fences, gates, bollards, site furniture.",
    grillOn: [
      "gate alignment vs slope",
      "bollard spacing vs truck turning radius",
      "fence post in utility conflict",
      "site furniture anchor vs asphalt patch",
      "security fence vs aesthetic veto",
      "powder coat damage at install",
    ],
    avoid: [
      "sprinkler hydraulic calc",
      "structural lateral system",
      "BIM clash matrix",
      "owner program workshop",
      "kitchen exhaust hood",
    ],
    angles: [
      "Gate swings — slope swings back.",
      "Bollards protect — from correct truck size.",
      "Fence line — utility line crossover episode.",
    ],
  },

  // ─── Demolition & abatement ───────────────────────────────────────────────
  demolition_contractor: {
    archetype: "Demolition contractor — selective demo, protection, sequencing, structural stability during demo.",
    grillOn: [
      "selective demo vs as-built fiction",
      "protection of occupied areas failure",
      "surprise structural system behind wall",
      "design still on sheet A-101",
      "demo sequence vs utility active",
      "hammer energy vs drawing assumptions",
    ],
    avoid: [
      "LEED scorecard optimization",
      "BIM federation standards",
      "owner lender inspection only",
      "lighting fixture schedule",
      "commissioning OPR writing",
    ],
    angles: [
      "Selective demo — selectively surprised.",
      "Protection installed — occupant still dusty.",
      "Design on A-101 — demo on reality.",
    ],
  },
  abatement_hazmat: {
    archetype: "Hazmat abatement contractor — asbestos, lead, containment, clearance testing.",
    grillOn: [
      "abatement scope surprise behind walls",
      "containment breach anxiety",
      "clearance test failure retest loop",
      "schedule impact vs owner's opening date",
      "regulatory paperwork vs actual removal",
      "surprise material in unexpected location",
    ],
    avoid: [
      "architect render aesthetics",
      "scheduler CPM logic",
      "curtain wall shop drawing",
      "MEP load calculations",
      "landscape design intent",
    ],
    angles: [
      "Survey said none — wall said otherwise.",
      "Containment tight — schedule tighter.",
      "Clearance passed — after clearance 2.",
    ],
  },

  // ─── Operations ───────────────────────────────────────────────────────────
  facility_management: {
    archetype: "Facility management / O&M — handover, assets, CMMS, maintenance, warranties.",
    grillOn: [
      "O&M manual novel vs CMMS reality",
      "asset tagging incomplete at turnover",
      "warranty claim denied — suggestion with paperwork",
      "inheriting every design shortcut",
      "preventive maintenance schedule vs staffing",
      "closeout binder vs Monday fire drill",
    ],
    avoid: [
      "preconstruction buyout optimism",
      "stamping engineering drawings",
      "clash detection naming",
      "earthwork compaction",
      "structural steel fabrication",
    ],
    angles: [
      "O&M manual thick — CMMS empty.",
      "Warranty valid — claim invalid.",
      "Turnover complete — assets TBD.",
    ],
  },
  building_operator: {
    archetype: "Building operator / engineer (owner) — run-state, BAS troubleshooting, access, tenant issues.",
    grillOn: [
      "BAS sequence vs tenant complaint",
      "Monday morning equipment alarm",
      "inherited design sin troubleshooting",
      "access control vs contractor key chaos",
      "energy bill vs design model promise",
      "tenant call vs as-built fiction",
    ],
    avoid: [
      "bid takeoff quantities",
      "shoring design",
      "architect revision clouds",
      "rebar lap tables",
      "procurement PO terms",
    ],
    angles: [
      "BAS optimized — tenant frozen.",
      "Alarm at 6am — design's gift.",
      "As-built accurate — on nobody's drawing.",
    ],
  },
};
