import type { Intensity } from "../../types";

export const MEP_GRILL_ON = [
  "plenum war lost on paper before field",
  "equipment schedule vs ceiling height lie",
  "duct sizing vs architect aesthetic soffit",
  "load calc assumptions vs actual envelope",
  "coordination with electrical panel room size",
  "energy model inputs vs VE massacre",
  "reflected ceiling plan hide-and-seek",
  "Copy of Copy of Duct family tree",
  "NOT FOR CONSTRUCTION honesty on drawings",
  "coordinates week 48 — still wrong",
  "TAB truth vs design fiction",
  "panel schedule vs field device count",
  "invert spot on paper vs field camera",
  "make-up air vs hood exhaust coordination",
];

export const MEP_AVOID = [
  "field TAB balancing report as their daily job (TAB contractor)",
  "superintendent hammer jokes and daily sequence",
  "AHJ permit wall as their output (regulatory)",
  "concrete pour flatness (concrete trade)",
  "render golden hour aesthetics (architect)",
  "Navisworks clash naming sessions (BIM)",
];

export const MEP_ANGLES = [
  "Plenum war — you drew the casualties.",
  "Equipment fits — ceiling height was a suggestion.",
  "Load calc assumptions — VE deleted half of them.",
  "Copy of Copy of Duct — family tree of regret.",
  "RCP hides MEP — MEP finds the ceiling anyway.",
  "NOT FOR CONSTRUCTION — honest, rare, appreciated.",
  "Coordinates week 48 — still arguing with structure.",
  "Panel schedule v12 — field has v0.5.",
  "One-line clean — field conduit abstract art.",
  "Equipment submittal or-equal gymnastics.",
  "Ceiling height 14 feet on paper — 9'-2\" in plenum.",
  "You coordinate MEP like jazz — nobody knows the key.",
  "Hood exhaust vs make-up air — coordination late, always.",
  "Energy model poetry — meter tells prose.",
  "Duct sizing vs soffit aesthetic — architect wins, physics loses.",
  "Invert spot lied — camera didn't.",
  "Fixture schedule vs rough-in reality.",
  "Short circuit calcs done — utility letter pending.",
  "Plenum decorative on architect drawing — war zone in field.",
  "You love a plenum — the plenum doesn't love you back.",
  "Equipment schedule fiction — submittal nonfiction.",
  "Load calc assumptions — envelope disagrees.",
  "Coordination on ceiling height — professionally a war crime.",
  "MEP hidden in RCP — classic smuggler energy.",
  "Design drawings start honest — NOT FOR CONSTRUCTION.",
  "You sized the duct — architect sized the hope.",
  "Panel room sized for schedule — not for heat.",
  "Vent routing vs beam surprise — Tuesday tradition.",
  "You coordinate like jazz — key unknown, volume loud.",
  "Plenum war casualties — you drew them, field buried them.",
];

export const MEP_ROAST_LINES: Record<Intensity, string[]> = {
  light: [
    "Hi {name}! Your reflected ceiling plan is where MEP goes to hide — briefly.",
    "Hi {name}! You love a plenum — the plenum doesn't love you back, respectfully.",
    "Hi {name}! Copy of Copy of Duct — your family tree is a cry for help.",
    "Hi {name}! Equipment schedule fiction — submittal nonfiction, classic.",
    "Hi {name}! Ceiling height on paper: generous — in the plenum: personal.",
    "Hi {name}! You coordinate MEP like jazz — nobody knows the key.",
    "Hi {name}! Load calc assumptions — the envelope has other plans.",
    "Hi {name}! Panel schedule v12 — field is still on v0.5, charming.",
    "Hi {name}! One-line diagram clean — field conduit is abstract art.",
    "Hi {name}! You hide MEP in the RCP — smuggler energy, architect approved.",
    "Hi {name}! Hood exhaust vs make-up air — coordination scheduled for later.",
    "Hi {name}! Energy model poetry — the meter will write prose.",
    "Hi {name}! Duct sizing vs soffit aesthetic — architect wins, physics sulks.",
    "Hi {name}! Invert spot on paper — field camera has questions.",
    "Hi {name}! Fixture schedule vs rough-in — reality is undefeated.",
    "Hi {name}! You sized the equipment — ceiling height sized your optimism.",
    "Hi {name}! Coordinates week 48 — still beefing with structure.",
    "Hi {name}! NOT FOR CONSTRUCTION on the cover — honesty we respect.",
  ],
  contractor: [
    "Hi {name}! Your equipment submittal is or-equal gymnastics — gold medal energy.",
    "Hi {name}! Your coordination on ceiling height is a war crime — professionally.",
    "Hi {name}! Plenum war — you drew the casualties before the field buried them.",
    "Hi {name}! Equipment fits on paper — ceiling height was a suggestion from the architect.",
    "Hi {name}! Load calc assumptions — VE deleted half and called it value.",
    "Hi {name}! Panel room sized for the schedule — not for heat or reality.",
    "Hi {name}! Duct vs soffit — architect aesthetic won, airflow lost.",
    "Hi {name}! RCP hide-and-seek — MEP found the ceiling anyway.",
    "Hi {name}! Short circuit calcs done — utility letter still pending, naturally.",
    "Hi {name}! Vent routing met a beam surprise — Tuesday tradition.",
    "Hi {name}! Make-up air vs hood exhaust — coordinated in theory, fought in field.",
    "Hi {name}! You coordinate like jazz — loud, improvisational, no key.",
    "Hi {name}! Equipment schedule vs field measure — measure wins, schedule sulks.",
    "Hi {name}! Ceiling 14 feet on drawing — MEP measured 9'-2\" and filed a report.",
    "Hi {name}! Copy of Copy of Pipe — naming convention of despair.",
    "Hi {name}! Energy model inputs — VE turned them into fan fiction.",
    "Hi {name}! You love coordinates — structure loves moving columns.",
    "Hi {name}! Design drawings honest upfront — NOT FOR CONSTRUCTION, rare integrity.",
  ],
  nuclear: [
    "Hi {name}! Your design drawings start with NOT FOR CONSTRUCTION — honest, brutal, fair.",
    "Hi {name}! You coordinate MEP like jazz — nobody knows the key, everyone plays loud.",
    "Hi {name}! Plenum war lost on paper — field fought it anyway, heroically.",
    "Hi {name}! You drew the casualties — superintendent buried them with RFIs.",
    "Hi {name}! Ceiling height lie — you measured it, architect denied it, plenum won.",
    "Hi {name}! Load calc assumptions vs envelope — envelope brought lawyers.",
    "Hi {name}! Equipment fits — if you delete the ceiling and the hope.",
    "Hi {name}! Panel schedule fiction — field device count is nonfiction horror.",
    "Hi {name}! You hide MEP in the RCP — MEP found the ceiling and your inbox.",
    "Hi {name}! Duct sizing vs architect soffit — physics lost, aesthetic won, building wheezes.",
    "Hi {name}! Coordinates week 48 — still wrong, still confident.",
    "Hi {name}! Energy model perfect — meter tells another story, rude.",
    "Hi {name}! You sized the duct — architect sized the denial.",
    "Hi {name}! Hood exhaust coordinated late — make-up air coordinated never.",
    "Hi {name}! One-line clean — field maze proves you optimistic.",
    "Hi {name}! You don't coordinate MEP — you document the war beautifully.",
    "Hi {name}! NOT FOR CONSTRUCTION — the most honest title in the set.",
    "Hi {name}! Plenum decorative on architect drawing — war zone in your career.",
  ],
  nsfw: [],
};
