import type { Intensity } from "../../types";

export const PM_GRILL_ON = [
  "meeting breeds meeting",
  "Gantt astrology with logos",
  "RAID log screams DESIGN",
  "blame matrix facilitation",
  "RFI backlog management theater",
  "recovery narrative with catering",
  "action items breeding action items",
  "lookahead fiction vs field citations",
  "minutes meetings — meetings minute you",
  "stakeholder aligned in invite only",
  "change review of reviews",
  "budget spreadsheet green — reality amber",
  "vendor coordination single point of failure",
  "owner directive translation failures",
  "sell certainty — deliver suspense",
];

export const PM_AVOID = [
  "clash naming as primary job (BIM)",
  "pretty render aesthetics (architect)",
  "stamping structural calcs",
  "writing 400-page spec (specifier)",
  "sprinkler head layout design",
  "duct rough-in in plenum (MEP trade)",
  "superintendent hammer jokes",
];

export const PM_ANGLES = [
  "Meetings about meetings — structural irony.",
  "Gantt green — field red.",
  "RAID log: screaming in columns, professionally.",
  "Action items breeding action items — nature is beautiful.",
  "Risk register is just DESIGN highlighted.",
  "You minutes meetings — the meetings minute you.",
  "Lookahead astrology with logos.",
  "You sell certainty — you deliver suspense.",
  "Recovery narrative with catering — never was on track.",
  "Blame matrix facilitation — rainbow of avoidance.",
  "RFI backlog management theater — sold out.",
  "Stakeholder aligned — in the meeting invite only.",
  "Change review — review of reviews.",
  "Budget spreadsheet green — reality amber.",
  "Owner directive translation — lost in meeting.",
  "Vendor coordination — you are the single point of failure.",
  "OAC deck is RFIs wearing business casual.",
  "Float ghosted — you still send it flowers.",
  "Master schedule fan fiction with logos.",
  "You don't run jobs — you host ongoing interventions.",
  "Coordination meeting has pre-game show.",
  "You facilitate blame — professionally, color-coded.",
  "Schedule recovery slide — field didn't get the deck.",
  "Your RAID screams DESIGN — accurate diagnosis.",
  "Meeting breeds meeting — inception energy.",
  "You promise handoffs — you deliver hot potatoes.",
  "Lookahead says Tuesday — RFI says season finale.",
  "You herd stakeholders — cats with budgets.",
  "Gantt astrology — Mercury in retrograde, professionally.",
  "You sell alignment — deliver suspense beautifully.",
];

export const PM_ROAST_LINES: Record<Intensity, string[]> = {
  light: [
    "Hi {name}! Action items breeding action items — nature is beautiful, meetings are fertile.",
    "Hi {name}! Your risk register is just DESIGN highlighted in yellow.",
    "Hi {name}! You minutes meetings — the meetings minute you, fairly.",
    "Hi {name}! Your coordination meeting has a pre-game show and a post-mortem.",
    "Hi {name}! Stakeholder aligned — in the meeting invite, at least.",
    "Hi {name}! Your RAID log is organized screaming — very professional font.",
    "Hi {name}! Gantt green on screen — field sending citations, politely.",
    "Hi {name}! You schedule hope — the lookahead schedules fiction.",
    "Hi {name}! Change review meeting — review of reviews, inception.",
    "Hi {name}! Your budget spreadsheet is green — reality is amber, trending red.",
    "Hi {name}! Vendor coordination — you are the single point of failure, heroically.",
    "Hi {name}! You translate owner directives — sometimes into more meetings.",
    "Hi {name}! OAC deck is RFIs wearing business casual — fashion forward.",
    "Hi {name}! You herd stakeholders like cats — cats with budgets and opinions.",
    "Hi {name}! Your action item list has grandchildren now.",
    "Hi {name}! Recovery narrative scheduled — recovery optional.",
    "Hi {name}! You sell alignment — delivery date is suspense genre.",
    "Hi {name}! Meeting invite accepted — problem solved, allegedly.",
  ],
  contractor: [
    "Hi {name}! Gantt is green — field citations needed, urgently.",
    "Hi {name}! You minutes meetings — the meetings minute you, daily.",
    "Hi {name}! Float is a concept you mention fondly in the past tense.",
    "Hi {name}! Your OAC deck is RFIs wearing business casual.",
    "Hi {name}! Blame matrix facilitation — rainbow of professional avoidance.",
    "Hi {name}! RFI backlog management theater — sold out, standing room.",
    "Hi {name}! Lookahead astrology with logos — constellations of denial.",
    "Hi {name}! Recovery narrative with catering — back on track fiction.",
    "Hi {name}! You facilitate meetings that create more meetings — inception.",
    "Hi {name}! Master schedule fan fiction — plot holes are features.",
    "Hi {name}! You promise handoffs — you deliver hot potatoes, hot.",
    "Hi {name}! RAID log screams DESIGN — accurate diagnosis, no cure.",
    "Hi {name}! Schedule recovery slide — superintendent didn't get the deck.",
    "Hi {name}! You sell certainty — suspense is your actual deliverable.",
    "Hi {name}! Coordination meeting breeds coordination meeting — family tree.",
    "Hi {name}! Owner directive translated — into three more workshops.",
    "Hi {name}! You don't run the job — you host ongoing interventions.",
    "Hi {name}! Float ghosted everyone — you still send it calendar invites.",
  ],
  nuclear: [
    "Hi {name}! Meetings about meetings — structural irony, load-bearing.",
    "Hi {name}! Your lookahead is astrology with logos — Mercury in retrograde, professionally.",
    "Hi {name}! You sell certainty — you deliver suspense, beautifully.",
    "Hi {name}! Your RAID log is just screaming in columns — font: professional.",
    "Hi {name}! Gantt fiction with logos — field writes the sequel in mud.",
    "Hi {name}! You don't close loops — you tie them in knots and schedule a review.",
    "Hi {name}! Blame matrix color-coded — you're the facilitator, not the villain, allegedly.",
    "Hi {name}! Recovery narrative audiobook — never was on track, still narrating.",
    "Hi {name}! RFI backlog is your lifestyle — management theater, sold out.",
    "Hi {name}! You lead meetings that create meetings — inception with catering.",
    "Hi {name}! Master schedule fan fiction — Pulitzer pending, field pending.",
    "Hi {name}! You herd cats — licensed trades, owners, and design, all opinionated.",
    "Hi {name}! Action items have action items — your to-do list is a genealogy site.",
    "Hi {name}! You promise clarity — deliver a scavenger hunt in meeting minutes.",
    "Hi {name}! OAC roundtable — RFIs in business casual, bold choice.",
    "Hi {name}! Lookahead says Tuesday — RFI log says season finale.",
    "Hi {name}! You sell alignment — stakeholders aligned in invite only.",
    "Hi {name}! You built a career on we'll recover in the next phase — which phase, exactly?",
  ],
  nsfw: [],
};
