import type { Intensity } from "../../types";

export const STRUCTURAL_GRILL_ON = [
  "SEE STRUCTURAL bubbles everywhere",
  "connection details deferred to steel detailer",
  "stamp Friday 4:58 transmittal energy",
  "calcs package vs sheet detail fiction",
  "verify-in-field as entire personality",
  "load path clear in heart — missing on PDF",
  "pin connection religion vs field buildability",
  "sketch on PDF as art — dimensions as suggestion",
  "redlines on redlines — turtles all the way down",
  "beam grew when architect moved a column",
  "deferred submittals as ticking gift to GC",
  "seismic notes thorough — dimension strings desert",
  "detail 3/S-501 says SEE STRUCTURAL — answer is good luck",
  "stamped Friday — Monday inherits deflection",
];

export const STRUCTURAL_AVOID = [
  "pretty render people on roof (architect)",
  "Navisworks clash naming comedy (BIM)",
  "owner VE smile deleting facade",
  "superintendent toolbox talk and hammer jokes",
  "Division 08 door hardware saga",
  "plenum war and Copy of Copy of Duct (MEP)",
];

export const STRUCTURAL_ANGLES = [
  "Calcs are church — sheet is fan fiction.",
  "Friday stamp — Monday inherits deflection.",
  "Pin connection nominally pinned — field nominally pissed.",
  "SEE STRUCTURAL — the industry's shrug emoji.",
  "Verify in field — three words, infinite RFIs.",
  "Connection detail novel — built connection improv.",
  "You stamp like closing a bar tab — physics opens Monday.",
  "Load path clear in your heart — missing on the PDF.",
  "Sketch on sheet is art — dimensions are suggestions.",
  "Beam grew two sizes — architect moved a column, you adapted.",
  "Detail calls out everything except the actual problem.",
  "Peer review is trauma bonding with math.",
  "Deferred submittal — ticking gift to the GC.",
  "Seismic notes thorough — dimension strings a desert.",
  "Redlines have redlines — turtles all the way down.",
  "You treat torsion like a personality trait.",
  "Steel detailer inherits your ambition and your gaps.",
  "Calcs fine — drawings cosplaying as calcs.",
  "You're why supers say engineering wanted it like a threat.",
  "Stamp energy Friday 4:58 — transmittal damage included.",
  "Foundation detail two lines — prayer sold separately.",
  "Lateral system clear in presentation — fuzzy in field.",
  "Connection design meeting — attendance optional, blame mandatory.",
  "Your RFI response time: geological.",
  "Field verify note — autobiography in shorthand.",
  "You love a cantilever — until the architect loves it more.",
  "Erection diagram clean — ironworker edition pending.",
  "Calc book thick — detail section thin.",
  "You export PDFs faster than you export clarity.",
  "Structural engineer: where physics meets polite denial.",
];

export const STRUCTURAL_ROAST_LINES: Record<Intensity, string[]> = {
  light: [
    "Hi {name}! Your redlines have redlines — it's turtles all the way down.",
    "Hi {name}! Blue text is your love language — red text is your alarm system.",
    "Hi {name}! SEE STRUCTURAL is your catchphrase — the industry's shrug emoji.",
    "Hi {name}! Your sketch on the PDF is art — your dimensions are suggestions.",
    "Hi {name}! You treat load paths like suggestions until Monday.",
    "Hi {name}! Connection detail is a novel — the built connection is improv.",
    "Hi {name}! Your calcs package is church — your sheet detail is fan fiction.",
    "Hi {name}! Pin connection religion — field practices a different denomination.",
    "Hi {name}! You defer to the steel detailer like it's a higher power.",
    "Hi {name}! Verify in field — three words, infinite superintendent side-eye.",
    "Hi {name}! Your seismic notes are thorough — your dimension strings are a desert.",
    "Hi {name}! Beam grew two sizes when the architect moved a column — you call that Tuesday.",
    "Hi {name}! Your detail calls out everything except the actual problem.",
    "Hi {name}! Peer review is trauma bonding with math and coffee.",
    "Hi {name}! You stamp with confidence — deflection arrives on its own schedule.",
    "Hi {name}! Foundation detail: two lines and a prayer, sold separately.",
    "Hi {name}! Your erection diagram is clean — ironworkers write the sequel.",
    "Hi {name}! Load path clear in your heart — fuzzy on the PDF, classic.",
  ],
  contractor: [
    "Hi {name}! The drawings were wrong eight minutes after mobilization — physics kept the receipt.",
    "Hi {name}! You found the error — after the concrete did, respectfully.",
    "Hi {name}! You stamp Friday — Monday inherits deflection and regret.",
    "Hi {name}! Calcs are fine — your dimensions are cosplaying as calcs.",
    "Hi {name}! Verify in field is your autobiography in three words.",
    "Hi {name}! Your connection detail is War and Peace — the field built a haiku.",
    "Hi {name}! Pin connection on paper — field connection is fan fiction.",
    "Hi {name}! You treat deferred submittals like gifts — the GC treats them like grenades.",
    "Hi {name}! SEE STRUCTURAL bubble — structural answer: good luck, king.",
    "Hi {name}! Your RFI response time is geological — supers evolved in the meantime.",
    "Hi {name}! Steel detailer inherited your ambition and your gaps — heroic.",
    "Hi {name}! You love a cantilever — until the architect loves it more than physics.",
    "Hi {name}! Lateral system clear in the presentation — fuzzy in the field photo.",
    "Hi {name}! Calc book thick — detail section thin — industry standard.",
    "Hi {name}! You're why supers say that's what engineering wanted — like a threat.",
    "Hi {name}! Friday 4:58 stamp — transmittal damage included, no extra charge.",
    "Hi {name}! Your sketch fixes problems — your dimensions create new ones.",
    "Hi {name}! Torsion isn't a detail — it's your personality, apparently.",
  ],
  nuclear: [
    "Hi {name}! Your calcs are fine — the drawings are cosplaying as calcs.",
    "Hi {name}! You stamp Friday — Monday inherits physics and everyone's mood.",
    "Hi {name}! Verify in field is your autobiography — and the field writes sequels.",
    "Hi {name}! Your detail calls out everything except the actual problem — bold strategy.",
    "Hi {name}! You treat load paths like suggestions — gravity does not negotiate.",
    "Hi {name}! Peer review is trauma bonding — the trauma is your dimension strings.",
    "Hi {name}! Connection detail novel — built connection is improv with liability.",
    "Hi {name}! SEE STRUCTURAL everywhere — you outsourced courage to the sheet index.",
    "Hi {name}! You export PDFs faster than you export clarity — impressive, wrong.",
    "Hi {name}! Beam grew when architecture sneezed — you called it adaptation.",
    "Hi {name}! Stamp energy Friday 4:58 — Monday's deflection is complimentary.",
    "Hi {name}! Your deferred submittals are ticking gifts — GC's inbox is the timer.",
    "Hi {name}! Calcs church — sheet fan fiction — field builds fan fiction's cousin.",
    "Hi {name}! You don't design connections — you imply them and transmittal.",
    "Hi {name}! Ironworkers trust you — the tape measure trusts nobody.",
    "Hi {name}! Seismic thorough — dimensions desert — a balanced diet of denial.",
    "Hi {name}! You're the reason RFIs have attachment limits — photos of hope dying.",
    "Hi {name}! Structural engineer: where physics meets polite, stamped denial.",
  ],
  nsfw: [],
};
