import type { Intensity } from "../../types";

export const SUPERINTENDENT_GRILL_ON = [
  "daily report: waiting on design",
  "RFI lifestyle and photo attachments",
  "trade coordination in mud",
  "schedule vs weather plot twists",
  "toolbox talk passive aggression",
  "sequence plan vs design radius change",
  "tape measure vs architect sketch",
  "mobilized on wrong sheet revision",
  "lookahead astrology with logos",
  "superintendent side-eye as power source",
  "field sketch art — wrong but art",
  "temp heat permanent like RFIs",
  "crew trusts you — drawings don't",
  "daily huddle stand-up about design",
];

export const SUPERINTENDENT_AVOID = [
  "Navisworks LOD slides and clash naming (BIM)",
  "stamping structural calcs Friday (engineer)",
  "owner lender TPR report writing",
  "LEED credit documentation treadmill",
  "writing MasterFormat specs (specifier)",
  "render golden hour aesthetics (architect)",
];

export const SUPERINTENDENT_ANGLES = [
  "Daily report religion: waiting on design.",
  "RFI photo — sheet A-101 still wrong.",
  "Sequence plan — weather had other plans.",
  "Tape measure gospel — architect sketch heresy.",
  "Toolbox talk: passive aggression training complete.",
  "Mobilized on revision that lied — tradition.",
  "Crew trusts you — drawings trust nobody.",
  "Field sketch wrong — still art, still built.",
  "Lookahead green — mud brown — schedule fiction.",
  "You swing clarity — design swings radius.",
  "Temp heat permanent — like your RFIs.",
  "Superintendent side-eye could power temp panels.",
  "Daily huddle: stand-up comedy about architects.",
  "You found the clash — where clashes retire.",
  "Schedule says Tuesday — rain says plot twist.",
  "Your RFI captions should win awards — wrong awards.",
  "Trade sequence plan — design changed the sequence.",
  "You trust survey until survey laughs back.",
  "As-builts aspirational — superintendent realistic.",
  "You don't read drawings — you negotiate with them.",
  "Hammer energy — respectfully, professionally, daily.",
  "Field production hero — inbox villain is design.",
  "You measure twice, curse once, RFI always.",
  "Your superintendent group chat has nicknames for everyone.",
  "Waiting on design — the industry's national anthem.",
  "You build fast — design builds mysteries.",
  "Sequence vs radius change — you felt it spiritually.",
  "Your daily report is bold — your patience is italic.",
  "You coordinate trades like cats — suddenly, loudly.",
  "Site photos always include one mysterious bucket.",
];

export const SUPERINTENDENT_ROAST_LINES: Record<Intensity, string[]> = {
  light: [
    "Hi {name}! Your daily huddle is stand-up comedy about design — crowd work is RFIs.",
    "Hi {name}! You trust the tape measure more than the architect's sketch — wise.",
    "Hi {name}! Your crew trusts you — the drawings trust nobody, respectfully.",
    "Hi {name}! Sequence plan gorgeous — weather had other plans, as usual.",
    "Hi {name}! Your field sketch is art — wrong, but art, and somehow built.",
    "Hi {name}! Toolbox talk doubles as passive aggression training — certified.",
    "Hi {name}! You schedule trades like Tetris — design keeps adding L-shaped pieces.",
    "Hi {name}! Daily report religion: waiting on design — amen.",
    "Hi {name}! Your lookahead is green — the mud is brown — classic contrast.",
    "Hi {name}! Temp heat is permanent — like your RFIs, like your patience.",
    "Hi {name}! You found the clash in the field — where clashes go to retire.",
    "Hi {name}! Site photos always include one mysterious bucket — tradition.",
    "Hi {name}! You measure twice, curse once, RFI always — lifestyle.",
    "Hi {name}! Your superintendent side-eye could power the temp panels.",
    "Hi {name}! Trade coordination in mud — glamour of the job.",
    "Hi {name}! You mobilized on optimism and a sheet that lied politely.",
    "Hi {name}! Rain day plot twist — your schedule didn't get the memo.",
    "Hi {name}! You coordinate subs the way cats coordinate — suddenly, loudly.",
  ],
  contractor: [
    "Hi {name}! You trust the tape measure more than the architect — gospel vs heresy.",
    "Hi {name}! RFI photo attached — sheet A-101 still wrong, still confident.",
    "Hi {name}! You mobilized before the ink dried — the drawing wasn't even final.",
    "Hi {name}! Your daily report is waiting on design in bold, every day.",
    "Hi {name}! Sequence plan vs design radius change — you felt it spiritually.",
    "Hi {name}! You don't read drawings — you negotiate with them, aggressively.",
    "Hi {name}! Field production hero — inbox villain is always design.",
    "Hi {name}! You build fast — design builds mysteries with revision clouds.",
    "Hi {name}! Your RFI subject lines read like horror titles — accurate.",
    "Hi {name}! Lookahead astrology with logos — field citations needed.",
    "Hi {name}! As-builts aspirational — superintendent realistic, as always.",
    "Hi {name}! You trust the survey until the survey laughs back.",
    "Hi {name}! Crane pick planned — nerves not included in the lookahead.",
    "Hi {name}! Your crew's group chat has nicknames for everyone — earned.",
    "Hi {name}! You treat tolerances like suggestions from a friend who lied.",
    "Hi {name}! Temp shoring permanent — like your RFIs, like your reputation.",
    "Hi {name}! You schedule trades like jazz — nobody knows the key.",
    "Hi {name}! Daily huddle stand-up about design — sold out every morning.",
  ],
  nuclear: [
    "Hi {name}! You swing that hammer like a F@#%N red squirrel — respect.",
    "Hi {name}! Your daily report is a religion called Waiting on Design — convert count: everyone.",
    "Hi {name}! You don't manage chaos — you franchise it with a hard hat.",
    "Hi {name}! Drawings wrong eight minutes after mobilization — you still built something, hero.",
    "Hi {name}! You found the error after concrete did — timing is everything.",
    "Hi {name}! Schedule says done — punch list says Netflix series.",
    "Hi {name}! You herd cats — the cats are licensed trades with opinions.",
    "Hi {name}! Design changed the radius — you changed everyone's weekend.",
    "Hi {name}! Your superintendent side-eye is a renewable energy source.",
    "Hi {name}! You mobilized on a sheet that lied — tradition, not tragedy.",
    "Hi {name}! RFI lifestyle — photo attachments are your content strategy.",
    "Hi {name}! You don't resolve clashes — you adopt them and build around them.",
    "Hi {name}! Field sketch wrong — built anyway — that's leadership.",
    "Hi {name}! Your toolbox talk is therapy — attendance mandatory, healing optional.",
    "Hi {name}! Waiting on design — you sing it, the crew harmonizes.",
    "Hi {name}! You treat rain like a plot twist in a show nobody ordered.",
    "Hi {name}! Tape measure gospel — architect sketch is fan fiction.",
    "Hi {name}! You built a career on we'll sort it in the field — and you did.",
  ],
  nsfw: [],
};
