import type { Intensity } from "../../types";

type TradeLines = Record<Intensity, string[]>;

export const CIVIL_ROAST_LINES: TradeLines = {
  light: [
    "Hi {name}! Your grading plan is poetry — your invert spot is a lie with confidence.",
    "Hi {name}! You treat the survey like a suggestion until something doesn't fit.",
    "Hi {name}! Storm vs sanitary on paper — field camera has opinions.",
    "Hi {name}! Paving section smooth — pothole tells the truth eventually.",
    "Hi {name}! Erosion control BMP vs rain event — rain always wins.",
    "Hi {name}! Utility coordination phone tree — despair on every branch.",
    "Hi {name}! ROW surprise — your schedule's favorite plot twist.",
    "Hi {name}! Cut/fill quantity art — survey surprise is the sequel.",
    "Hi {name}! Geotech report gospel — field soil heresy.",
    "Hi {name}! Site plan gorgeous — maintenance budget isn't, but the plan is.",
    "Hi {name}! Invert spot on paper — camera at the manhole disagrees.",
    "Hi {name}! Grading vs as-built mud — classic civil romance.",
    "Hi {name}! You love a paving detail — subgrade loves a surprise.",
    "Hi {name}! Easement fiction — discovered at the worst possible week.",
    "Hi {name}! BMP installed — rain event uninstalls, tradition.",
    "Hi {name}! Utility conflict at 3am — civil's nightlife.",
    "Hi {name}! Sitework on schedule — AHJ on their own calendar.",
    "Hi {name}! Your drainage calcs are church — field is fan fiction.",
  ],
  contractor: [
    "Hi {name}! Your utility coordination is a phone tree of despair — everyone's on hold.",
    "Hi {name}! Your paving section shows smooth — the pothole shows truth.",
    "Hi {name}! Invert spot lied — the camera didn't, respect to the camera.",
    "Hi {name}! Utility conflict discovered at 3am — civil engineer nightlife.",
    "Hi {name}! Grading plan vs as-built mud — you felt it in the rut.",
    "Hi {name}! Storm pipe fiction — sanitary pipe has its own novel.",
    "Hi {name}! Compaction test failed — rework is your cardio.",
    "Hi {name}! ROW easement surprise — schedule's favorite villain.",
    "Hi {name}! Geotech said clay — field said plot twist.",
    "Hi {name}! Cut/fill quantity vs survey — survey brought receipts.",
    "Hi {name}! Erosion BMP vs rain — rain is undefeated.",
    "Hi {name}! Paving detail pretty — subgrade told another story.",
    "Hi {name}! Utility coordination meeting — phone tree of blame.",
    "Hi {name}! Sitework hero — entitlement timeline is fan fiction.",
    "Hi {name}! Invert on paper — ironworker of utilities says otherwise.",
    "Hi {name}! You call it sitework — the rain calls it content.",
    "Hi {name}! Drainage design clean — field pond disagrees.",
    "Hi {name}! Easement discovered — everyone's favorite Tuesday.",
  ],
  nuclear: [
    "Hi {name}! Your entitlement timeline is fan fiction with a stamp — bold genre.",
    "Hi {name}! You call it sitework — the AHJ calls it content for months.",
    "Hi {name}! Invert spot fiction — camera nonfiction — building nonfiction.",
    "Hi {name}! Grading plan poetry — as-built mud is the devastating sequel.",
    "Hi {name}! Utility conflict at 3am — you don't sleep, you coordinate.",
    "Hi {name}! Storm vs sanitary fiction — field merges them creatively.",
    "Hi {name}! Geotech gospel — field heresy — lawsuit optional.",
    "Hi {name}! BMP vs rain event — rain writes the punchline.",
    "Hi {name}! ROW surprise — your schedule never saw it coming, somehow.",
    "Hi {name}! Cut/fill art — survey surprise — tragedy in three acts.",
    "Hi {name}! Paving smooth on paper — pothole is the reviewer.",
    "Hi {name}! You design drainage — water designs its own path, rude.",
    "Hi {name}! Easement fiction discovered — everyone's weekend updated.",
    "Hi {name}! Sitework on drawing — AHJ on their own timeline, always.",
    "Hi {name}! Utility phone tree of despair — you are the trunk.",
    "Hi {name}! Erosion control vs weather — weather is the final boss.",
    "Hi {name}! Your grading plan is poetry — reality is a harsh critic.",
    "Hi {name}! Civil engineer: where inverts lie and cameras tell truth.",
  ],
  nsfw: [],
};

export const MEP_TRADE_ROAST_LINES: TradeLines = {
  light: [
    "Hi {name}! Your rough-in is where design dreams go to die — respectfully.",
    "Hi {name}! Plenum war — you fight it daily, design watches from the RCP.",
    "Hi {name}! Copy of Copy of Duct in the field — family reunion of regret.",
    "Hi {name}! Rough-in interference — your specialty, design's surprise.",
    "Hi {name}! Submittal or-equal — you read cheapest wins, accurately.",
    "Hi {name}! Ceiling grid level — height wasn't, but grid is.",
    "Hi {name}! You love a plenum — it loves fighting back.",
    "Hi {name}! Equipment set — coordination was fiction, you improvised.",
    "Hi {name}! Duct install art — design drawing was abstract.",
    "Hi {name}! TAB report pending — your rough-in already told stories.",
    "Hi {name}! Sprinkler head vs ceiling tile — weekly negotiation.",
    "Hi {name}! Conduit maze — one-line diagram was optimistic.",
    "Hi {name}! You rough-in first — blame arrives last, tradition.",
    "Hi {name}! Or-equal submittal — design's trap, your lifestyle.",
    "Hi {name}! Plenum decorative on drawing — war zone in your shift.",
    "Hi {name}! Field measure gospel — design sketch heresy.",
    "Hi {name}! You install what fits — design drew what dreams.",
    "Hi {name}! MEP trade: last to claim space, first to get blamed.",
  ],
  contractor: [
    "Hi {name}! Your TAB report is truth — your coordination was fiction, fairly.",
    "Hi {name}! You own the plenum — the architect thought it was decorative.",
    "Hi {name}! Rough-in interference discovered — design sends thoughts and prayers.",
    "Hi {name}! Or-equal submittal approved — field installed cheapest, accurately.",
    "Hi {name}! Plenum war daily — design war monthly, if lucky.",
    "Hi {name}! Equipment doesn't fit — ceiling height lied, you adapted heroically.",
    "Hi {name}! Duct vs beam — beam wins Tuesdays.",
    "Hi {name}! Conduit abstract art — one-line was optimistic fan fiction.",
    "Hi {name}! Sprinkler head fight — ceiling tile negotiates poorly.",
    "Hi {name}! You rough-in in mud — design rough-in in Revit, cute.",
    "Hi {name}! TAB truth arrives — design fiction already shipped.",
    "Hi {name}! Last in plenum — first in blame chain, tradition.",
    "Hi {name}! Submittal approved — field improvisation still required.",
    "Hi {name}! You install MEP — design installs hope in the RCP.",
    "Hi {name}! Plenum war casualties — you are the memorial.",
    "Hi {name}! Field sketch fixes design — invoice fixes your weekend.",
    "Hi {name}! Rough-in clash — found in field, where clashes retire.",
    "Hi {name}! You own the plenum — nobody owns the blame, except you.",
  ],
  nuclear: [
    "Hi {name}! You own the plenum — architect thought it was negative space, wrong.",
    "Hi {name}! TAB report truth — coordination fiction — design fan fiction.",
    "Hi {name}! Rough-in where dreams die — you bury them with skill.",
    "Hi {name}! Plenum war — you fight, design watches, superintendent narrates.",
    "Hi {name}! Or-equal trap — you installed it, design denied it, GC invoiced it.",
    "Hi {name}! Last in plenum — first in blame chain — load-bearing irony.",
    "Hi {name}! Equipment doesn't fit — ceiling height was a suggestion from hell.",
    "Hi {name}! You don't coordinate — you survive and document with photos.",
    "Hi {name}! Duct vs beam — beam undefeated, duct adapted, respect.",
    "Hi {name}! Design drew jazz — you installed prose with cursing.",
    "Hi {name}! TAB says fail — design says schedule — you say overtime.",
    "Hi {name}! Rough-in interference — your career, design's footnote.",
    "Hi {name}! Plenum decorative on A-101 — your shift is the war documentary.",
    "Hi {name}! You install truth — drawings install suspense.",
    "Hi {name}! MEP trade: where hope goes to get couplings.",
    "Hi {name}! Field improvisation required — submittal optional, apparently.",
    "Hi {name}! You fight the plenum — the plenum fights back, daily.",
    "Hi {name}! Design dreams died here — you signed the death certificate with pipe.",
  ],
  nsfw: [],
};

export const ENVELOPE_ROAST_LINES: TradeLines = {
  light: [
    "Hi {name}! Your air barrier detail is a rumor at the laps — gossip, professionally.",
    "Hi {name}! Flashing detail energy — strong at the mockup, shy in the field.",
    "Hi {name}! Cladding mock-up passed — field has questions.",
    "Hi {name}! WRB continuity — theoretical at the penetration.",
    "Hi {name}! Deflection surprise — your specialty, structure's gift.",
    "Hi {name}! Sealant joint pretty — movement joint has opinions.",
    "Hi {name}! Water test scheduled — water test unscheduled itself.",
    "Hi {name}! Air barrier laps — rumor mill at the corner.",
    "Hi {name}! Glazing deflection — mullion tolerance fiction.",
    "Hi {name}! Roofing penetration — flashing detail TBD, classic.",
    "Hi {name}! Mockup chef's kiss — field lap shrug.",
    "Hi {name}! You love a detail section — water loves a gap.",
    "Hi {name}! Cladding alignment gorgeous — substrate disagrees.",
    "Hi {name}! Thermal bridge hand-waved — camera not hand-waved.",
    "Hi {name}! Envelope consultant report thick — lap joint thin.",
    "Hi {name}! Curtain wall meeting — glass, hope, leakage eventual.",
    "Hi {name}! Air barrier tested — air found the workaround.",
    "Hi {name}! You detail continuity — field details discontinuity.",
  ],
  contractor: [
    "Hi {name}! Your cladding mock-up passed — the field failed, respectfully.",
    "Hi {name}! Air barrier detail rumor — water confirmed the gossip.",
    "Hi {name}! Mockup passed — water found the gap anyway.",
    "Hi {name}! Continuity detail exists — in the report appendix.",
    "Hi {name}! Thermal bridge hand-waved with confidence — camera disagreed.",
    "Hi {name}! Flashing laps — rumor at the corner, truth at the leak.",
    "Hi {name}! Deflection surprise — mullion tolerance was fiction.",
    "Hi {name}! WRB continuity — penetration had other plans.",
    "Hi {name}! Sealant joint pretty — building movement wrote sequel.",
    "Hi {name}! Water test pass — first rain event writes review.",
    "Hi {name}! Cladding gorgeous — substrate told another story.",
    "Hi {name}! Glazing install clean — deflection drama pending.",
    "Hi {name}! Roofing penetration — flashing detail missing in action.",
    "Hi {name}! Air barrier tested — air is creative.",
    "Hi {name}! Mockup chef's kiss — field shrugged and leaked.",
    "Hi {name}! You own waterproofing — water owns the schedule.",
    "Hi {name}! Detail section jewelry — lap joint is costume jewelry.",
    "Hi {name}! Envelope trade: where gaps get Yelp reviews.",
  ],
  nuclear: [
    "Hi {name}! Water found the gap — it left a review, one star, detailed.",
    "Hi {name}! Air barrier rumor at laps — water confirmed journalism.",
    "Hi {name}! Mockup passed — field failed — building failed — trilogy complete.",
    "Hi {name}! You sell continuity — water sells intrusion, aggressively.",
    "Hi {name}! Flashing detail missing — leak detail present, vivid.",
    "Hi {name}! Deflection surprise — mullion tolerance was fan fiction.",
    "Hi {name}! WRB continuity theoretical — penetration practical.",
    "Hi {name}! Cladding museum quality — back-of-wall where souls leak.",
    "Hi {name}! Thermal bridge hand-waved — energy model cried.",
    "Hi {name}! Water test pass — rain event wrote the real test.",
    "Hi {name}! You don't waterproof — you negotiate with physics.",
    "Hi {name}! Detail section stunning — lap joint is the plot twist.",
    "Hi {name}! Curtain wall: glass, hope, leakage — accurate marketing.",
    "Hi {name}! Air barrier tested — air found the social loophole.",
    "Hi {name}! Mockup lied confidently — field confessed under oath.",
    "Hi {name}! Envelope trade: Yelp reviews written in streaks.",
    "Hi {name}! You own the gap — water owns the narrative.",
    "Hi {name}! Continuity in report — discontinuity in wall — classic.",
  ],
  nsfw: [],
};

export const REGULATORY_ROAST_LINES: TradeLines = {
  light: [
    "Hi {name}! Your plan check comment is the real schedule — accurate.",
    "Hi {name}! Resubmittal cycle — your cardio, everyone's patience.",
    "Hi {name}! Code interpretation hold — final boss energy, polite.",
    "Hi {name}! Comment letter volume — War and Peace, Division AHJ.",
    "Hi {name}! You are the gate — fear is justified, professionally.",
    "Hi {name}! Permit wall decorative — until it isn't.",
    "Hi {name}! Entitlement timeline — you write the plot twists.",
    "Hi {name}! Redlines petty — undefeated, respect.",
    "Hi {name}! Final boss of entitlement — title earned.",
    "Hi {name}! Plan check queue — where hope queues.",
    "Hi {name}! Your comment is concise — pain is comprehensive.",
    "Hi {name}! Code section cited — soul crushed, cited.",
    "Hi {name}! Resubmittal three — charm offensive optional.",
    "Hi {name}! AHJ review — industry's speed bump collection.",
    "Hi {name}! You hold the permit — everyone holds their breath.",
    "Hi {name}! Comment letter arrives — schedule updates itself, downward.",
    "Hi {name}! Compliance scan needed — you are the scan.",
    "Hi {name}! Plan check Friday — mobilization Monday, comedy.",
  ],
  contractor: [
    "Hi {name}! You are the AHJ — fear is justified, documented.",
    "Hi {name}! Redlines petty — and undefeated, hall of fame.",
    "Hi {name}! Comment letter drops — GC calendar clears, magically.",
    "Hi {name}! Resubmittal cycle four — design team therapy session.",
    "Hi {name}! Code hold — everyone's favorite season.",
    "Hi {name}! Plan check comment — real schedule driver, honest.",
    "Hi {name}! Entitlement final boss — you have the controller.",
    "Hi {name}! Permit delayed — project delayed — blame matrix updated.",
    "Hi {name}! Your redline is one line — impact is one quarter.",
    "Hi {name}! AHJ interpretation — gospel until appealed.",
    "Hi {name}! Comment petty — impact structural, ironically.",
    "Hi {name}! You gatekeep permits — gatekeeping is the job.",
    "Hi {name}! Resubmittal rejected — design team auditions for drama.",
    "Hi {name}! Plan check queue longer than the building timeline.",
    "Hi {name}! Code section weaponized — professionally, politely.",
    "Hi {name}! You hold compliance — project holds breath.",
    "Hi {name}! Final inspection energy — everyone's nervous, including you.",
    "Hi {name}! AHJ comment — small font, large consequences.",
  ],
  nuclear: [
    "Hi {name}! Your redlines are petty — and undefeated, legendary.",
    "Hi {name}! You are the final boss — no cheat codes, no DLC.",
    "Hi {name}! Comment letter volume — industry trauma, bound in PDF.",
    "Hi {name}! Plan check is the real schedule — Gantt is fan fiction.",
    "Hi {name}! Resubmittal cycle — Sisyphean, with stamps.",
    "Hi {name}! Code hold — project holds breath, budget holds funeral.",
    "Hi {name}! Petty redline — massive impact — art form.",
    "Hi {name}! You gatekeep permits — gate is load-bearing.",
    "Hi {name}! Entitlement timeline — you are the plot twist factory.",
    "Hi {name}! AHJ review — where optimism goes to comment.",
    "Hi {name}! Permit wall real — GC wall decorative, finally.",
    "Hi {name}! Your interpretation is gospel — until the appeal hearing.",
    "Hi {name}! One comment — six weeks — math checks out, painfully.",
    "Hi {name}! You don't approve — you season projects with fear.",
    "Hi {name}! Plan check Friday 4pm — mobilization fiction.",
    "Hi {name}! Redline petty — consequence structural — poetry.",
    "Hi {name}! Final boss energy — no save points.",
    "Hi {name}! Regulatory: where PDFs go to get humbled.",
  ],
  nsfw: [],
};

export const COMMISSIONING_ROAST_LINES: TradeLines = {
  light: [
    "Hi {name}! Your functional test is where design sins surface — politely.",
    "Hi {name}! Cx checklist long — O&M manual longer, somehow.",
    "Hi {name}! You commission systems — optimism is optional.",
    "Hi {name}! Functional test fail — design sin revealed, gently.",
    "Hi {name}! TAB overlap finger-pointing — you referee professionally.",
    "Hi {name}! Cx plan thick — field truth thicker.",
    "Hi {name}! Pre-functional checklist — design fiction audit.",
    "Hi {name}! You test systems — systems test everyone's patience.",
    "Hi {name}! O&M manual vs reality — your Monday content.",
    "Hi {name}! Cx visit scheduled — sins reschedule too.",
    "Hi {name}! Witness test energy — popcorn optional.",
    "Hi {name}! Design promised performance — you measure actual.",
    "Hi {name}! Checklist item 400 — still finding sins.",
    "Hi {name}! You commission hope — meter commissions truth.",
    "Hi {name}! Functional test — design's report card.",
    "Hi {name}! Cx authority — polite, thorough, feared.",
    "Hi {name}! Systems integrated — blame not integrated, yet.",
    "Hi {name}! You surface sins — design surfaces slides.",
  ],
  contractor: [
    "Hi {name}! Your Cx checklist is longer than the O&M manual — impressive.",
    "Hi {name}! Functional test fail — design sin promoted to headline.",
    "Hi {name}! You commission systems — everyone commissions excuses.",
    "Hi {name}! TAB overlap — finger-pointing Olympics, you judge.",
    "Hi {name}! Pre-functional fail — design fiction audit failed.",
    "Hi {name}! Witness test — design team attendance optional, shame mandatory.",
    "Hi {name}! Cx plan vs field — field writes unauthorized sequel.",
    "Hi {name}! O&M manual fiction — your test nonfiction.",
    "Hi {name}! Performance test — design slides vs meter prose.",
    "Hi {name}! Checklist 400 items — sin 401 discovered.",
    "Hi {name}! You surface design sins — politely, with forms.",
    "Hi {name}! Integrated systems — disintegrated blame, classic.",
    "Hi {name}! Cx visit — GC performance art debut.",
    "Hi {name}! Functional test where optimism dies — professionally.",
    "Hi {name}! You test — they explain — you test again.",
    "Hi {name}! Design intent vs Cx result — gap measurable.",
    "Hi {name}! Commissioning: design's finals week, everyone's GPA.",
    "Hi {name}! Sin surfaced — RFI spawned — tradition.",
  ],
  nuclear: [
    "Hi {name}! You commission systems — you decommission optimism, thoroughly.",
    "Hi {name}! Functional test fail — design sin gets a documentary.",
    "Hi {name}! Cx checklist epic — design sins epic-er.",
    "Hi {name}! You surface every sin — design surfaces every slide.",
    "Hi {name}! Performance test — meter tells truth — design tells story.",
    "Hi {name}! O&M manual fiction — your test is nonfiction horror.",
    "Hi {name}! Integrated test — disintegrated team — fair trade.",
    "Hi {name}! You don't commission — you audit design's conscience.",
    "Hi {name}! Witness test — shame mandatory, attendance optional.",
    "Hi {name}! Pre-functional fail — design fiction audit: F.",
    "Hi {name}! TAB overlap blame Olympics — gold for everyone.",
    "Hi {name}! Cx authority feared — sins respectfully exposed.",
    "Hi {name}! Checklist item 400 — sin 401 was hiding.",
    "Hi {name}! You test systems — systems test careers.",
    "Hi {name}! Design promised — you measured — gap is load-bearing.",
    "Hi {name}! Commissioning: where hope goes to get a report.",
    "Hi {name}! Functional test — design's autopsy, polite.",
    "Hi {name}! You decommission optimism — building commissioning sold separately.",
  ],
  nsfw: [],
};

export const SUSTAINABILITY_ROAST_LINES: TradeLines = {
  light: [
    "Hi {name}! Your LEED score is high — your envelope isn't, awkward.",
    "Hi {name}! Credit documentation treadmill — your cardio.",
    "Hi {name}! Energy model poetry — meter will write prose.",
    "Hi {name}! Material red list chase — paperwork Olympics.",
    "Hi {name}! WELL point math vs VE massacre — classic.",
    "Hi {name}! Submittal credit form filed — field substitution filed faster.",
    "Hi {name}! LEED Platinum on slides — Bronze in submittals.",
    "Hi {name}! Credit form vs field — field is creative.",
    "Hi {name}! You sell carbon — paperwork delivers first.",
    "Hi {name}! Energy model inputs — VE edited the plot.",
    "Hi {name}! Commissioning overlap — finger-pointing scheduled.",
    "Hi {name}! Sustainability report thick — envelope thin.",
    "Hi {name}! Meter performance pending — slides already won award.",
    "Hi {name}! Credit chase — design chase — same treadmill.",
    "Hi {name}! You document green — field documents beige.",
    "Hi {name}! LEED checklist — industry's homework.",
    "Hi {name}! Envelope performance — slide performance — gap measurable.",
    "Hi {name}! You count points — building counts leaks.",
  ],
  contractor: [
    "Hi {name}! Your energy model is poetry — the meter is prose, harsh.",
    "Hi {name}! Credit documentation treadmill — no finish line.",
    "Hi {name}! LEED Platinum slides — Bronze submittals — accurate.",
    "Hi {name}! VE massacre vs credit math — math lost.",
    "Hi {name}! Field substitution vs credit form — substitution faster.",
    "Hi {name}! Energy model perfect — built meter tells another story.",
    "Hi {name}! Material red list — obsolete SKU hunt, weekly.",
    "Hi {name}! Commissioning overlap — blame scheduled concurrently.",
    "Hi {name}! Envelope score low — slide score high — irony.",
    "Hi {name}! You sell sustainability — RFIs sell reality.",
    "Hi {name}! Credit form filed — field improvised — points pending.",
    "Hi {name}! WELL points vs budget — budget wins, points sulk.",
    "Hi {name}! Meter prose — model poetry — gap is genre.",
    "Hi {name}! Documentation treadmill — hamster is you.",
    "Hi {name}! LEED checklist longer than the building warranty.",
    "Hi {name}! You chase credits — trades chase schedule.",
    "Hi {name}! Green on paper — beige in ceiling tile.",
    "Hi {name}! Sustainability consultant: paperwork hero, envelope villain.",
  ],
  nuclear: [
    "Hi {name}! You sell carbon — you deliver RFIs, plot twist.",
    "Hi {name}! LEED Platinum slides — building performance Bronze — trilogy.",
    "Hi {name}! Energy model poetry — meter prose — lawsuit genre optional.",
    "Hi {name}! VE deleted the envelope — kept the credit slide, bold.",
    "Hi {name}! Credit documentation treadmill — no exit, no water.",
    "Hi {name}! Field substitution killed the credit — slide still wins award.",
    "Hi {name}! You count points — water counts gaps.",
    "Hi {name}! Sustainability report novel — building performance footnote.",
    "Hi {name}! Meter tells truth — model told story — gap load-bearing.",
    "Hi {name}! Material red list chase — SKU obsolete before submittal.",
    "Hi {name}! You sell green — you deliver paperwork forest.",
    "Hi {name}! WELL math vs VE — math lost, building wheezes.",
    "Hi {name}! Commissioning finds sins — you find credit forms.",
    "Hi {name}! Envelope failed — slide passed — industry standard.",
    "Hi {name}! You document sustainability — building documents leakage.",
    "Hi {name}! Credit chase is career — performance chase is optional.",
    "Hi {name}! LEED checklist — homework nobody graded until occupancy.",
    "Hi {name}! Sustainability: where slides are Platinum and walls are drafty.",
  ],
  nsfw: [],
};

export const ESTIMATOR_ROAST_LINES: TradeLines = {
  light: [
    "Hi {name}! Your takeoff assumes the drawing is telling the truth — brave.",
    "Hi {name}! Bid spread shock — your Tuesday face.",
    "Hi {name}! Quantity takeoff art — drawing fiction is the muse.",
    "Hi {name}! Allowance for revisions — cute number, honestly.",
    "Hi {name}! You trust the PDF — the PDF trusts nobody.",
    "Hi {name}! Buyout optimism — your love language.",
    "Hi {name}! Assumption log fiction — industry folklore.",
    "Hi {name}! Takeoff software gospel — field heresy pending.",
    "Hi {name}! Bid day adrenaline — design day ambiguity.",
    "Hi {name}! You count bricks — architect counts vibes.",
    "Hi {name}! Scope gap discovered — priced as allowance, wisely.",
    "Hi {name}! Estimator spreadsheet green — reality amber.",
    "Hi {name}! Drawing set for bid — drawing set lies politely.",
    "Hi {name}! Trade boundary gap — your specialty.",
    "Hi {name}! You assume — famous last words, documented.",
    "Hi {name}! Takeoff complete — revision cloud incoming.",
    "Hi {name}! Bid due Friday — drawing final never.",
    "Hi {name}! Quantity art — unit price science — you blend both.",
  ],
  contractor: [
    "Hi {name}! Your allowance for design revisions is cute — revision cloud disagrees.",
    "Hi {name}! Takeoff assumes truth — drawing set assumes fiction.",
    "Hi {name}! Bid spread shock — subs brought receipts.",
    "Hi {name}! Buyout done — surprises just beginning, tradition.",
    "Hi {name}! Assumption log — folklore with your signature.",
    "Hi {name}! Drawing set used for bid — used for lies, accurately.",
    "Hi {name}! Trade boundary gap — priced as TBD, heroically.",
    "Hi {name}! Scope packaging art — gaps are the medium.",
    "Hi {name}! You assumed — GC famous last words.",
    "Hi {name}! Takeoff gospel — addendum heresy.",
    "Hi {name}! Bid art — buyout tragedy — genre shift.",
    "Hi {name}! Quantity takeoff — revision cloud is the sequel.",
    "Hi {name}! Estimator vs precon — same spreadsheet, different prayer.",
    "Hi {name}! Allowance cute — change order not cute.",
    "Hi {name}! You price hope — field prices reality.",
    "Hi {name}! Bid day hero — mobilization villain is the drawing.",
    "Hi {name}! Takeoff trusts PDF — superintendent trusts tape measure.",
    "Hi {name}! Buyout spread — everyone's surprised, except you, barely.",
  ],
  nuclear: [
    "Hi {name}! Your bid is art — the buyout is tragedy, award-winning.",
    "Hi {name}! Takeoff assumes truth — drawing set is fan fiction.",
    "Hi {name}! Allowance for revisions — revision cloud laughed.",
    "Hi {name}! You assumed — industry famous last words, stamped.",
    "Hi {name}! Bid spread shock — subs brought trauma and numbers.",
    "Hi {name}! Buyout optimism died — spreadsheet held funeral.",
    "Hi {name}! Assumption log fiction — buyout nonfiction horror.",
    "Hi {name}! You price the drawing — field prices the surprise.",
    "Hi {name}! Quantity art — change order is the critique.",
    "Hi {name}! Drawing set for bid — mobilization on wrong sheet, classic.",
    "Hi {name}! Trade boundary gap — priced as hope.",
    "Hi {name}! Estimator: where PDFs lie and spreadsheets cry.",
    "Hi {name}! Bid due Friday — IFC never — comedy.",
    "Hi {name}! You don't estimate — you negotiate with fiction.",
    "Hi {name}! Buyout brave — lookahead poetry — field prose.",
    "Hi {name}! Takeoff complete — addendum incoming — tradition.",
    "Hi {name}! Your bid wins — your buyout loses — balanced career.",
    "Hi {name}! Assumptions folder — industry's horror anthology.",
  ],
  nsfw: [],
};
